### ISSUE TITLE
Browse Data - Chart x-axis labels

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#10]
### Steps to reproduce the problem

![image](https://user-images.githubusercontent.com/29519901/27441380-fd4db028-5732-11e7-9610-089d7fe08800.png)

### Form Name: ReporteDiario

Due to users are defined as emails, those string are too long to be displayed correctly. Also dates, etc

**Comment by nap2000** [comment]
A checkbox has been added to the chart set up.  This can be selected to show the default labels for the axis.  If unselected the name will be shown instead.  For example the following may be the setup for a choice value:
     name:  home
     label:  Place where you spend most of your time
