### ISSUE TITLE
URGENT - BUG - standard template does not diplay all questions

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#101]

**Comment by nap2000** [comment]
Can you be a bit more precise?
The template generation changed in the last release to not include fields where there was no answer unless they are "note" type.  What fields are not being shown that should be?

**Comment by atl2017** [comment]
It is displaying only text:

[survey (6).pdf](https://github.com/smap-consulting/smapserver/files/1329428/survey.6.pdf)

It is not including select_one with yes/no answer.  Due to privacy I will send form by email

**Comment by atl2017** [comment]
Thanks
