### ISSUE TITLE
Traslation Buttons 

### ISSUE THREAD

**Issue by ztatu** [smap-consulting/smapserver#11]
### Actual Behaviour: "Add Chart", "Map Layers", "Add Map"

![image](https://user-images.githubusercontent.com/29519901/27441912-77616e76-5734-11e7-955c-a893f6071d37.png)

![image](https://user-images.githubusercontent.com/29519901/27441957-94a73880-5734-11e7-8fc6-368bdfb43fa2.png)

**Comment by nap2000** [comment]
Fixed
