### ISSUE TITLE
M - ENHANCEMENT - F5.07- Control FT version installed previos to start to collect data.

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#112]

**Comment by atl2017** [comment]
@nap2000 Today we are depending on user to update FT. Users have options to auto-update by Play Store but it only happens if is set auto-update for ALL apps. So normally, users unmark this option. Whe users are few is under control, but if number of users is high is? Think about a mandatory update due to a bug (like #81 related to ODK)

What is proposed is just to have a settings that when is checked from server demand to update app or goes to link where apk is.

![screenshot-1507046343168](https://user-images.githubusercontent.com/29519901/31135351-5b86a256-a82a-11e7-8f50-7c84e1f16a66.jpg)

![screenshot-1507046343168](https://user-images.githubusercontent.com/29519901/31135361-64932752-a82a-11e7-9aa5-de142e310cdd.jpg)

**Comment by nap2000** [comment]
I agree it would be useful to track which version of fieldTask a user is using.  However it is only considered high priority because the last version contained the automatic synchronisation that enables synchronisation.  Given that this change could only apply to versions of fieldTask launched after its implementation then it can't really be considered high priority.

I will see if I can include it in the next release.

**Comment by atl2017** [comment]
Or just a simple notification that a new version of FT is available with link to play store when app starts

**Comment by atl2017** [comment]
Maybe a solution could be to check VersionName with some string set in server at FieldTask Options (ie: FT Version) if it is different just go to link to play. Similar when you click in "Leave a review on the Google Play Store". In fact, this string should become to "Update app"

![screenshot-1510146042719](https://user-images.githubusercontent.com/29519901/32575416-ec7473b8-c4a1-11e7-81f8-890537dc1c0a.jpg)
![screenshot-1510146054382](https://user-images.githubusercontent.com/29519901/32575430-f83a6ffe-c4a1-11e7-884b-5ab59593b16f.jpg)

**Comment by atl2017** [comment]
ODK started to work in this matter:  [https://forum.opendatakit.org/t/notifying-users-in-app-about-app-updates/10846](https://forum.opendatakit.org/t/notifying-users-in-app-about-app-updates/10846)

**Comment by atl2017** [comment]
Just close to wait for ODK improvement
