### ISSUE TITLE
High Priority - URGENT - HELP - WebForm display an error message with a particular form

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#117]
### Actual Behaviour
Form cannot be completed using webform. Error message displayed:

![image](https://user-images.githubusercontent.com/29519901/31841166-e7aa8a96-b5ad-11e7-962c-50c710fa2a01.png)

### Steps to reproduce the problem

(Optional) If this is reproducible on a Smap hosted server then include

**Comment by nap2000** [comment]
Have you checked the csv file for the unterminated quote?

**Comment by atl2017** [comment]
Neil. Thanks!

I feel a little bit stupid not reading well Error message
