### ISSUE TITLE
ENHANCEMENT - Notify when Notification is not received between specific date-time

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#119]
### Expected Behaviour: What if we include a notification when a main notification has not been received between two dates-time (start - end).

The idea is to create an alert system to monitor that jobs is being done, if not, triggering an alternative notification to communicate that some task has not been accomplished or form has not been filled out

### Actual Behaviour
Maybe include as part of new filtering..

![image](https://user-images.githubusercontent.com/29519901/32020899-4f97b0b0-b997-11e7-8bc7-9621f9917be4.png)

**Comment by nap2000** [comment]
Try now using the reserved word _upload_time or referring to a date in your survey. For example:
`_upload_time > '2017-11-07' and _upload_time < '2017-11-09'`

**Comment by atl2017** [comment]
Tested with your example an OK.  In these case, notification is triggered by the next submission indicating that there were not submissions a period before that. Is it possible to triggered that notification by local time. I mean like an alarm that alerts that a submission has not been received yet.

On the other hand it would be nice to include time in addition to dates

**Comment by atl2017** [comment]
Another comment, when you can work in #23 we could match notification filters with columns from tasks creation and trigger accomplisment i.e  something like   ${ _upload_time} = ${_from_time}

**Comment by atl2017** [comment]
Questions: 1 - Does ${_upload_time} take server time or local time?   
                  2- Is it possible to include not only day but hour?  If yes, what is the format?  Could you provide an example?
