### ISSUE TITLE
HIGH 2 - ENHACEMENT - New Security Group: Editor to limit access to edit/change/create forms..

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#121]

**Comment by atl2017** [comment]
I think is better to inlcude a new Security Group: editor
![image](https://user-images.githubusercontent.com/29519901/33208587-213c0b98-d0e0-11e7-9173-54fb0d55c11e.png)

that handles:

![image](https://user-images.githubusercontent.com/29519901/33208669-6f5d9c4c-d0e0-11e7-9691-1248b95a7dda.png)

Also is necessary to limit access to modify data (Delete, Mark as bad, Modify)

![image](https://user-images.githubusercontent.com/29519901/33208816-15410798-d0e1-11e7-9fde-8ed8025314f5.png)

A suggestion could be to include in settings as "Allow loading data from file"

![image](https://user-images.githubusercontent.com/29519901/33209039-0b9dd792-d0e2-11e7-8298-42be5e1b3b25.png)

**Comment by atl2017** [comment]
Neil, 

At least consider to have a simple configuration like this. Its is very important to split Analyst:

![image](https://user-images.githubusercontent.com/29519901/34755424-e90efeac-f591-11e7-8ab0-e48e1fe2d3a0.png)

**Comment by nap2000** [comment]
Hi looking at this now.   However I would rather not add the new group editor and reduce permissions on analyst.  This would make migration of existing systems difficult.  Even if it just meant that the name "analyst" would be replaced with "editor" and then a new "analyst group would be created with reduced permissions then it would be confusing for other people.  

Hence I am thinking of adding a new group "view data".  Thoughts?

**Comment by atl2017** [comment]
Agree. What is important is to have access only to see data and not edit
form or change in any way.

Also roles should be apply to limit either columns or rows.

Thanks.

El 18 ene. 2018 9:26 PM, "Neil Penman" <notifications@github.com> escribió:

Hi looking at this now. However I would rather not add the new group editor
and reduce permissions on analyst. This would make migration of existing
systems difficult. Even if it just meant that the name "analyst" would be
replaced with "editor" and then a new "analyst group would be created with
reduced permissions then it would be confusing for other people.

Hence I am thinking of adding a new group "view data". Thoughts?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/smap-consulting/smapserver/issues/121#issuecomment-358847846>,
or mute the thread

**Comment by nap2000** [comment]
Updated to allow downloading of PDF and to hide control buttons that allow export, import and delete.

**Comment by atl2017** [comment]
Tested Ok, but maybe it should be good to eliminate Edit in WebForm, because after click and being unauthorised, app logged out

![image](https://user-images.githubusercontent.com/29519901/35179091-de7c16e2-fd60-11e7-9f5c-45b4f7a34101.png)
![image](https://user-images.githubusercontent.com/29519901/35179102-1ebff958-fd61-11e7-9317-c5d93ee37a4b.png)
![image](https://user-images.githubusercontent.com/29519901/35179105-340fd846-fd61-11e7-90ad-5ecfc82aba52.png)

**Comment by atl2017** [comment]
Not big deal, but is a better UX. So it is up to you to close or fix the issue.

**Comment by atl2017** [comment]
Thanks OK

**Comment by atl2017** [comment]
Check that this Security Group have access to API https://app.kontrolid.com/api/v1/data/xxxx and would not. It should behaves as Enumerator that display

![image](https://user-images.githubusercontent.com/29519901/35397972-dbf14b06-01be-11e8-8df0-81ebce81855f.png)
