### ISSUE TITLE
H - BUG Cannot import data file 

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#127]
### Actual Behaviour: File cannot be imported using Analysis --> Import.  I am not sure if situation is related to Range question types.

![image](https://user-images.githubusercontent.com/29519901/32401340-4fd420e6-c0da-11e7-86c5-922e1eea538f.png)

### Steps to reproduce the problem

(Optional) If this is reproducible on a Smap hosted server then include

### Form Name:  R-0501 - EvaluacionCalidadServicio

Try upload this file

[R-0501 - EvaluacionCalidadServicio.zip](https://github.com/smap-consulting/smapserver/files/1442829/R-0501.-.EvaluacionCalidadServicio.zip)

**Comment by nap2000** [comment]
Yes you are correct.  Its the range question.  Its been fixed and I will put out a patch soon.

**Comment by atl2017** [comment]
Tested Ok
