### ISSUE TITLE
BUG - Upload tag file failed

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#135]
### Actual Behaviour: Tags file is uploaded but after refreshing si not displayed. Also is not visible to assign task

![image](https://user-images.githubusercontent.com/29519901/32499438-916dde16-c3a0-11e7-954f-8786213af312.png)
![image](https://user-images.githubusercontent.com/29519901/32499459-a5cad828-c3a0-11e7-8340-06020d0cf222.png)

### Steps to reproduce the problem
[locations.xlsx](https://github.com/smap-consulting/smapserver/files/1450416/locations.xlsx)

### Project: TestAlex
Shared Resources

**Comment by nap2000** [comment]
It looks like the tags were being uploaded OK and are available to use in tasks however they do not show as available NFC on the resources page.   I have made a patch release that I will upload today.

**Comment by atl2017** [comment]
Tested OK. Thanks
