### ISSUE TITLE
ENHACEMENT - Use question name as label in calculate questions

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#136]
### Actual Behaviour: When you use Form Editor to create a calculate question by default server assign as label name a consecutive predesign name.

![image](https://user-images.githubusercontent.com/29519901/32609777-c3fc2128-c52e-11e7-9565-f03b002e8f1e.png)

**Comment by nap2000** [comment]
Calculates should not have a label.  When exporting a form to XLS the label will now be blanked out if it is a calculate.  I haven't changed to generation of XML that will still include the calculate label this is ignored by collect.

**Comment by atl2017** [comment]
Tested OK. Thanks
