### ISSUE TITLE
BUG - multiline appereance is not working

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#138]
### Expected Behaviour: multiline should be wotk as 

![image](https://user-images.githubusercontent.com/29519901/32673983-4286a0e0-c61f-11e7-9098-6d7cdda54263.png)

### Actual Behaviour:

![image](https://user-images.githubusercontent.com/29519901/32673944-17949a04-c61f-11e7-8b0e-62a0fb94964e.png)

![image](https://user-images.githubusercontent.com/29519901/32673955-242b3912-c61f-11e7-9c13-320757b8bbb3.png)

### Steps to reproduce the problem

(Optional) If this is reproducible on a Smap hosted server then include

**Comment by nap2000** [comment]
Fixed. You can also set rows=xx in parameters now to change the number of rows in fieldTask.

**Comment by atl2017** [comment]
great!

Tested OK:

![image](https://user-images.githubusercontent.com/29519901/32728525-a567391e-c84e-11e7-8888-6cee1f719d41.png)
