### ISSUE TITLE
URGENT - BUG - Edit in web form is not working

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#140]
### Actual Behaviour:

![image](https://user-images.githubusercontent.com/29519901/32961251-d4a0c8a4-cb95-11e7-9a66-6574572c176c.png)

![image](https://user-images.githubusercontent.com/29519901/32961216-ab4dfeea-cb95-11e7-9be2-f2c8e4d536f1.png)

### Steps to reproduce the problem: Does not worh in all forms

(Optional) If this is reproducible on a Smap hosted server then include

**Comment by nap2000** [comment]
I tried that survey and saw the issue.  However after I pressed refresh on the browser the problem went away and I couldn't reproduce it.  Will look further.

**Comment by atl2017** [comment]
Now is OK. Thanks
