### ISSUE TITLE
M2- BUG - User trail is not working

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#141]
### Actual Behaviour: User trail does not show any data. I think after FT 5.0+ is not working

![image](https://user-images.githubusercontent.com/29519901/33072601-317a789a-ce8e-11e7-83c0-f2f630819e13.png)

**Comment by nap2000** [comment]
Yes it still needs to be added to the latest ft.

**Comment by atl2017** [comment]
Tested ok. Thanks a lot
