### ISSUE TITLE
BUG 5- ANALYSIS - Survey choices list do not highlight blocked forms

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#148]
### Actual Behaviour: List show all forms:

![image](https://user-images.githubusercontent.com/29519901/33482249-1f3652aa-d666-11e7-89f5-b91d70dbeb4e.png)

**Comment by nap2000** [comment]
Why do you not want to see the data for forms that are blocked?  Blocked just stops more data from being added to a form it does not stop you using or viewing the data that has been collected.  If you are done with the form you could just delete it.

**Comment by atl2017** [comment]
Sorry if I was not enogh clear. What I need is to see what forms are blocked (As it was before). Now current list does not differentiate which are activated and which are deactivated.

**Comment by nap2000** [comment]
I'm still not sure why there is value in seeing which forms are blocked in the analysis page.  If you don't want to access the data any more you should delete the survey rather than block it.

**Comment by atl2017** [comment]
Blocked data are data with important data to remain stored but in an older version. Thats why I consider is important to differentiate. But you are right. Not big deal with this matter.
