### ISSUE TITLE
Improvement - SMS Notifications

### ISSUE THREAD

**Issue by ztatu** [smap-consulting/smapserver#15]
### Actual Behaviour: SMS is not included

Hi Neil,

I was thinking that due to latest improvements in text notifications by Email, the next step to change the way message is sent from Email to SMS could be straightforward just adding a choice SMS in Target (see below)

![1](https://user-images.githubusercontent.com/29519901/27443791-d73a764e-5739-11e7-8072-0f59fc904b97.jpg)

SMS gateway could be set in Organisation Level

and a similar question as Email Question could be added as Phone Number Question

Regards,

Alexander

**Comment by nap2000** [comment]
Implemented.  This solution was designed specifically for requesting organisations needs and sends an SMS using their SMS provider.  It can be added for anyone where their provider supplies a URL for sending SMS messages.  Contact Smap support if you need it.

**Comment by ztatu** [comment]
Works perfect. It is needed a setting form to customised parameters (user/password). It  should be like SMTP settings: One by server (SMS service link below Email server port) and another by organisation (SMS service link in Other options or a new SMS Options block).  Thats due to each organisation would have its own account.

**Comment by ztatu** [comment]
Could you please reopen issue to consider my comments above

**Comment by nap2000** [comment]
Can you open a new issue.
