### ISSUE TITLE
BUG 3 - 17.12 - answer from select_one from external csv shows many repeated numbers in pdf template

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#151]
### Actual Behaviour:

![image](https://user-images.githubusercontent.com/29519901/33644611-e52da44e-da13-11e7-8124-a0103270c802.png)

[132381-TEMPOCOLBA-2017-12-05.pdf](https://github.com/smap-consulting/smapserver/files/1533882/132381-TEMPOCOLBA-2017-12-05.pdf)

### Steps to reproduce the problem: Just download pdf report and see displayed data for  
  La cantidad entregada de COFIA AZUL CON MALLA Y VIVO BLANCO GRUPO COLBA es?: (Select_one from external file into a repeat group) or:

La cantidad entregada de UNIFORME AUX. DAMA TURQUI T:M TEMPO es?:

**Comment by atl2017** [comment]
Tested and Fixed

**Comment by atl2017** [comment]
Again!

PDF template:
![image](https://user-images.githubusercontent.com/29519901/35012650-7e7ae8f2-fad8-11e7-88eb-d2a28eaeebfc.png)

XlSform:

![image](https://user-images.githubusercontent.com/29519901/35012691-9ef88a8a-fad8-11e7-8546-02bb51a94128.png)

Generated PDF:

![image](https://user-images.githubusercontent.com/29519901/35012616-5a064692-fad8-11e7-84a7-71d9489a000d.png)

**Comment by nap2000** [comment]
Its not clear to me that this is a bug.  Q3 is a select multiple.  Did you not select those options?

**Comment by atl2017** [comment]
Yes but see that it duplicates answer. It is shown twice. see highlighted and not

**Comment by atl2017** [comment]
[survey (4).pdf](https://github.com/smap-consulting/smapserver/files/1855500/survey.4.pdf)

tested OK
