### ISSUE TITLE
BUG - 17.12 - Warning message "Question name not found" after uploading data

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#153]
### Actual Behaviour: When you download data and upload again in Analysis there is a warning message about "question name missing":

![image](https://user-images.githubusercontent.com/29519901/34202819-ea9a566e-e546-11e7-8cb2-dacf3f222881.png)

### Steps to reproduce the problem: Upload attache file to form: Testusername
[TestUsername.zip](https://github.com/smap-consulting/smapserver/files/1575146/TestUsername.zip)

**Comment by nap2000** [comment]
Fixed in 17.12

**Comment by atl2017** [comment]
Tested OK.

**Comment by atl2017** [comment]
Appears again! either in English or Spanish:

![capturaanalysis2](https://user-images.githubusercontent.com/29519901/34997947-c836ffda-faab-11e7-8172-a8eac561ca0c.JPG)
![capturaanalysis1](https://user-images.githubusercontent.com/29519901/34997948-c857aab4-faab-11e7-8466-111c68efadd3.JPG)

**Comment by atl2017** [comment]
Not big deal. Apparently is some kind of incompatibilty with former forms. But it was with a test, so a customer request.

![image](https://user-images.githubusercontent.com/29519901/35276803-a637ba66-0012-11e8-83b5-f1ea577917e2.png)

**Comment by atl2017** [comment]
Issue again:

In Spanish:

![capturaimport1](https://user-images.githubusercontent.com/29519901/37731488-3ab8cc0a-2d10-11e8-9228-c0b47b290732.JPG)

In English:
![image](https://user-images.githubusercontent.com/29519901/37731506-4545c8ee-2d10-11e8-8dee-7df0edc898b6.png)

**Comment by nap2000** [comment]
Fixed again.   If you export data and then reimport it you should find all columns are imported now.  The meta data items in the exported file will be labelled using their underlying column name for example _start, _end rather than the translated name.  This allows matching of columns to happen independent of the language of the user.

**Comment by atl2017** [comment]
tested OK

![image](https://user-images.githubusercontent.com/29519901/37878766-92a1d1a2-3033-11e8-9419-179a9eef502e.png)
