### ISSUE TITLE
BUG - SMAP 17.12 - Roles setting pages is not working

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#156]
### Actual Behaviour: Roles settings page is not working and also when select user profile it get empty form

![image](https://user-images.githubusercontent.com/29519901/34494308-e4a6ba6e-efbd-11e7-9166-034d6df38ae9.png)

![image](https://user-images.githubusercontent.com/29519901/34494345-1b9756aa-efbe-11e7-8836-89ca2a89237f.png)

### Steps to reproduce the problem: link to: [Survey Roles Settings](https://app.kontrolid.com/surveyRoles.html)

(Optional) If this is reproducible on a Smap hosted server then include

**Comment by nap2000** [comment]
You need to provide more information including the security groups and
roles thst the user belongs to.

**Comment by atl2017** [comment]
With my user admin I checked all available roles and I tried to assign one
to one form. No one is display neither project nor forms lists as is shown
in images.

**Comment by nap2000** [comment]
Do you have the security manager group?

**Comment by atl2017** [comment]
Please check (Same happens with Firefox):

[Video: Steps to reproduce the problem](https://drive.google.com/open?id=1-jeck4NrfxVHhxsz9X8GU_8DryRcij0D)

**Comment by atl2017** [comment]
Tested OK.

Now I understand how to set Roles int he Xlsform. Great feature that let easily admin Roles

Survey sheet:
![image](https://user-images.githubusercontent.com/29519901/34650132-c04100d8-f389-11e7-95f6-20d7b93c64bc.png)

Settings sheet:
![image](https://user-images.githubusercontent.com/29519901/34650137-ceeba020-f389-11e7-850c-bfd92f36d71d.png)
