### ISSUE TITLE
BUG - SMAP 17.12 - SMS Notification deactivated

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#159]
### Server: Kontrolid

![image](https://user-images.githubusercontent.com/29519901/34571001-68695ad6-f13b-11e7-814c-bd4cb8400fd6.png)

**Comment by atl2017** [comment]
Tested OK

**Comment by nap2000** [comment]
Ok great.  Tomorrow you will be able to modify the url.  Change the
password etc.  In the meantime if the server options are updated sms will
stop working.

**Comment by atl2017** [comment]
Thanks. In the future it would be work as smtp, with chance to be set by
organisation in addition to general setting.
