### ISSUE TITLE
BUG - SMAP 17.12 - TRANSIFEX Error Message

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#160]
### Actual Behaviour: space and variable missing in message (either englisg and spanish)

![image](https://user-images.githubusercontent.com/29519901/34641463-c057d446-f2d2-11e7-8e89-832bd46d7d6a.png)

**Comment by atl2017** [comment]
I tested again and do not produce any message no matter error is still present:

![image](https://user-images.githubusercontent.com/29519901/34650291-c2d739e0-f38c-11e7-9137-7c45b8715804.png)

Project: TestAlex
Form: TestCSVMultiple3

In choices sheet there is

![image](https://user-images.githubusercontent.com/29519901/34650298-f04ed806-f38c-11e7-9418-0a3a9cf21714.png)

and in the csv file there are no header with this name:

![image](https://user-images.githubusercontent.com/29519901/34650304-0c4b0d2c-f38d-11e7-9a20-69ab6ae5aa4d.png)

**Comment by nap2000** [comment]
Yes.  I made a modification to just send the error to the log.  My thinking was that it may not be a real errors as the intention maybe to edit the csv later.   If upload supported warnings then this might be appropriate but it doesn't at the moment.    

However on reflection I think this should be reported as an error.  Loading an xls form that references a CSV file that does not exist is ok (maybe should also be a warning) as the expectation would be that the CSV file will be loaded next.  However if the CSV file is already there and it does not match then its probably a mistake.  So I will add the error report back in.

**Comment by nap2000** [comment]
I've added a warning message for when the CSV files exist but the references from the xlsform do not match the columns in the CSV file.

**Comment by atl2017** [comment]
tested OK

![image](https://user-images.githubusercontent.com/29519901/34723197-a6f8ee94-f517-11e7-92a4-3b76b48cb0a6.png)
