### ISSUE TITLE
BUG - 17.12 - Error trying to replace a Form with the same XLSForm

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#163]
### Actual Behaviour:

After downloading XLSForm and replace by itself with no change following error message is displayed when tried to download pdf 

![image](https://user-images.githubusercontent.com/29519901/34736011-806e20e6-f53f-11e7-9512-e51b73a74aca.png)

### Steps to reproduce the problem

[Video](https://drive.google.com/open?id=1C0JUy8mW2DMPis1BsRkXIF5Y0fttABwK)

(Optional) If this is reproducible on a Smap hosted server then include

**Comment by atl2017** [comment]
I tried with another form: TestImages and works fine ONLY if I erased metada questions as was downloaded.

![image](https://user-images.githubusercontent.com/29519901/34892249-86e49f54-f7a6-11e7-8e5e-cd4647f84b18.png)

I supposed then that situation is related with database structure and there are some differences between xlsform as downloaded and needed.

**Comment by nap2000** [comment]
The error was caused by there not being any data in select multiple questions in the sub fom.  I've fixed this now.  I presume not having any data in that subform was correct?

**Comment by atl2017** [comment]
No Neil, situation still remains.

Please try to do it by yourself. I recovered Data (See image below), is OK except I cannot download PDF because there is an error with HTML labels.

 So I  have two ways to fix: 
1 - Using form editor but #161
2- Use xlsform and replace: [Find here New Xlsform](https://drive.google.com/open?id=1uZUY1O3bNkm4mQKfK6JPUFG-6eFDoeji)

2nd is what I trying to do but fails.
Organisation: Zarkman Project: TestAlex Form:  R-0905. Registro de Información para Cotización y Visitas Técnicas V1

![image](https://user-images.githubusercontent.com/29519901/34937085-8cd74256-f9b1-11e7-8b32-36687c1277fe.png)

**Comment by atl2017** [comment]
As before. Data got lost (All Tables becomes Undefined).

**Comment by nap2000** [comment]
Ok i couldnt reproduce that with forms i crested. Can you detail the steps

**Comment by atl2017** [comment]
1- Go to Manage Forms and download R-0905. Registro de Información para Cotización y Visitas Técnicas V1

![image](https://user-images.githubusercontent.com/29519901/34939313-5fe12ed0-f9b9-11e7-93bf-433b911a65b6.png)
![image](https://user-images.githubusercontent.com/29519901/34939381-97ca270c-f9b9-11e7-9714-de24973c1071.png)

2- Open Xlsform and edit row 7 to change from calculate to username. (optional you can erase all metadata rows except start ) ¿could start be the problem?

![image](https://user-images.githubusercontent.com/29519901/34939477-e86357a6-f9b9-11e7-93ac-c71427dae1c5.png)

Save and replace:

![image](https://user-images.githubusercontent.com/29519901/34939508-0276cb3c-f9ba-11e7-9f74-57578db59f14.png)

Check Analysis... and verify tables

**Comment by nap2000** [comment]
Ok excellent!  Its the old issue of capitals letters in question names which I am always not testing for!  I will put out a release to fix this overnight tonight your time.

**Comment by atl2017** [comment]
No Neil, situation still happens:

![image](https://user-images.githubusercontent.com/29519901/34998180-5e3d8e0e-faac-11e7-94d3-44e74ff5d251.png)

Situation is with main table.

**Comment by atl2017** [comment]
Tested with TestCSVMultiple3.xlsx maybe is very specific to a above form, that is a test. So I will close.
