### ISSUE TITLE
ENHANCEMENT - Include filter by role in Users page

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#174]
### Expected Behaviour: Include an additional filter to display users with specific role

![image](https://user-images.githubusercontent.com/29519901/35331138-385c79a6-00d4-11e8-97e1-2bbb7e7de76b.png)

**Comment by atl2017** [comment]
Tested OK.

Transifex Done. I suggest to include this.

![image](https://user-images.githubusercontent.com/29519901/35484264-b8f7f672-041b-11e8-8a1d-af7ec498a128.png)

What about to include and index 1,2,3,4....n in order to have a fast look of how many users do we have

**Comment by nap2000** [comment]
Not sure how the index suggestion would work.

**Comment by atl2017** [comment]
Ok. Understood.

Or just a count like 8 of 25 users.

It also help me for fast check about number of users. But it is not big
deal, just low priority.
