### ISSUE TITLE
ENHANCEMENT - Special Filter to add: ${username} = current()

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#176]

**Comment by atl2017** [comment]
One possibly implementation could be by add a new Security Group: "Only User´s Data". The idea is that as a User you can only view Data that you have collected (username)

![image](https://user-images.githubusercontent.com/29519901/38737257-49aba084-3ef4-11e8-8b5c-6f98577a7578.png)

**Comment by atl2017** [comment]
Hi Neil, I am reopening this issue due to was requested for another customer.

Basic need is how to see only records I did in an easy way, In other words user's column in tables = logged user in a click.

**Comment by nap2000** [comment]
Released on sg server.  refer to http://www.smap.com.au/docs/admin-users.html

**Comment by atl2017** [comment]
Tested with API.

OK displaying record of own user
![image](https://user-images.githubusercontent.com/29519901/69093253-17a0d600-0a1c-11ea-9975-69f72667c7d7.png)
but some links failed:

1- PDF report:
![image](https://user-images.githubusercontent.com/29519901/69093342-3dc67600-0a1c-11ea-9428-e50618b4d6eb.png)
2- WEB FORM: asked again for log in, but after that OK. Display data to edit:
![image](https://user-images.githubusercontent.com/29519901/69093493-8a11b600-0a1c-11ea-9dde-7eeeb4570a6e.png)

3- AUDIT: Fail (Expected behaviour)

**Comment by nap2000** [comment]
OK I shall add PDF support.   The user with "view own data" privilege can also see their data on the console if they also have the manage privilege.

**Comment by atl2017** [comment]
Tested Ok. 

Thanks
