### ISSUE TITLE
H3 - ENHANCEMENT - 18.01 - Include ${username} as question to filter by

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#180]
### Actual Behaviour: It is not possible to use advance filter with metadata ${username} and it is so useful

![image](https://user-images.githubusercontent.com/29519901/35545814-0d4bda58-053f-11e8-9c39-6935420a4539.png)

**Comment by nap2000** [comment]
It works with preloads like username or email.  You need to remember to mark the checkbox to include preloads when using the new XLS export.  Also you need to refer to the name that you used when specifying the preload.

 It doesn't work with the name that the user is logged on as.  Is that what you wanted?

**Comment by atl2017** [comment]
Yes, I am refering to metadata. I checked again and works for filter in Notifications, Exports in New XLSX but not for Legacy XLSX.

Also is not working in advanced filtering for rows in Role setting 

![image](https://user-images.githubusercontent.com/29519901/35784083-1b8a892e-09e1-11e8-94b6-8b706680a62d.png)


![image](https://user-images.githubusercontent.com/29519901/35784078-0ff5ab8e-09e1-11e8-9250-16fe7d3a467f.png)


![image](https://user-images.githubusercontent.com/29519901/35784074-03f3689e-09e1-11e8-9f9a-c17b2ff73249.png)

**Comment by atl2017** [comment]
I tested again and works. Maybe it is not working properly with some former forms.
