### ISSUE TITLE
HIGH - BUG - username and/or email metadata is not visible as Email question in Notification

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#183]
### Actual Behaviour: username and/or email metadata is not visible as Email question in Notification

![image](https://user-images.githubusercontent.com/29519901/35683290-7d6ee3ae-0731-11e8-89a7-b9564184be6b.png)

![image](https://user-images.githubusercontent.com/29519901/35683392-bbd2253e-0731-11e8-9582-6746a5f67ee2.png)

**Comment by nap2000** [comment]
Preloads are now treated separately from questions in Smap.  Places where you could select preloads they are no longer available.   I have now added a separate drop down to the notification dialog to allow you to select a "non question" type such as a preload as the source of an email address.

**Comment by atl2017** [comment]
Ok. It is visible as you mention. But I havn´t received any notification at all!

![image](https://user-images.githubusercontent.com/29519901/35729192-f38e713a-07db-11e8-8fff-7d4bbbf22df1.png)
![image](https://user-images.githubusercontent.com/29519901/35730174-15e2587a-07df-11e8-9fa2-e9627470b10f.png)
![image](https://user-images.githubusercontent.com/29519901/35730208-32cf91c8-07df-11e8-8b7f-b83f199be99c.png)
![image](https://user-images.githubusercontent.com/29519901/35729157-cf94469c-07db-11e8-81ba-0d10e415a796.png)

**Comment by nap2000** [comment]
You set up the email on the device?

**Comment by atl2017** [comment]
Yes and as username. I am checking also because I haven´t receive the SMS as testing

**Comment by nap2000** [comment]
I need to add the description in the notification table.  I tested the use
of the email user meta data on my dev machine and it sent an email there.

**Comment by atl2017** [comment]
Now is OK. Apparently was a situation with form that had role specif. I will check with more testing.
I erased those and works oK. Thanks a lot

![image](https://user-images.githubusercontent.com/29519901/35731620-57091064-07e4-11e8-93aa-1ae8dc15648d.png)

![image](https://user-images.githubusercontent.com/29519901/35731631-662b2f5a-07e4-11e8-9d63-e415b3f5a854.png)

**Comment by atl2017** [comment]
In order to have a better UX, this new option should list only username and email. Because they are the only variable with sense
![image](https://user-images.githubusercontent.com/29519901/35731839-3b9c0380-07e5-11e8-87c8-4991e9abde98.png)

**Comment by atl2017** [comment]
#185 was what happened. Thats why I could not see notifications
