### ISSUE TITLE
BUG - Date / Time is printed in pdf as UTC instead of local time as before

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#188]
### Actual Behaviour: Apparently one of the effects of latest update is that Dates - Hour aren´t in local time anymore:

![image](https://user-images.githubusercontent.com/29519901/35885009-829af728-0b5a-11e8-8359-a235976081e4.png)

**Comment by atl2017** [comment]
Still displaying in UTC + 00. See differences below. It should be UTC - 05 in local time

![image](https://user-images.githubusercontent.com/29519901/35965983-87541020-0c8a-11e8-8d03-f2293554d9b9.png)

![image](https://user-images.githubusercontent.com/29519901/35966028-abd57a1a-0c8a-11e8-95bf-8013abd524e4.png)

**Comment by atl2017** [comment]
Confirmed with new survey. It has not been fixed yet:

![image](https://user-images.githubusercontent.com/29519901/35969360-9379cb24-0c94-11e8-9ca7-4ececd3e68f1.png)

![image](https://user-images.githubusercontent.com/29519901/35969381-a5e57100-0c94-11e8-9243-039772b9ef93.png)

**Comment by atl2017** [comment]
Neil,

Apparently issue is with date-time widget:

![image](https://user-images.githubusercontent.com/29519901/36184051-8db02192-10ff-11e8-9d36-f1c319c487af.png)

**Comment by nap2000** [comment]
Oh are there countries west of Europe!   Yep I wasn't dealing with -ve time zones.

**Comment by atl2017** [comment]
Tested OK. Thanks a lot.

![image](https://user-images.githubusercontent.com/29519901/36204395-2667839a-1159-11e8-94bc-ae28b737c8db.png)

![image](https://user-images.githubusercontent.com/29519901/36204447-514e9292-1159-11e8-8d4b-6f63de179f71.png)
