### ISSUE TITLE
BUG - EDIT IN WEB FORM GENERATE INTERNAL ERROR 500

### ISSUE THREAD

**Issue by ztatu** [smap-consulting/smapserver#19]
### Expected Behaviour: Analysis in web forms works properly

![image](https://user-images.githubusercontent.com/29519901/27615691-b7c86b7e-5b6f-11e7-96f8-e71d49da64d0.png)
### Actual Behaviour:  Internal error 500 in many forms. Not all

![image](https://user-images.githubusercontent.com/29519901/27615682-a295d8e0-5b6f-11e7-97f4-014b5fcfe192.png)

### Form Name:  EncuestaSatisfaccionLogitem works OK but  EncuestaSatisfaccionMediosTec does not. Forms are almost the same.

Also organisation: push Projects: All  organisation: terrazas project: all

**Comment by nap2000** [comment]
Fixed
