### ISSUE TITLE
ANALYSIS - QUICK? - ENHANCEMENT- Include parkey  as variable in filter

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#198]
### Expected Behaviour: Include parkey (Record) as variable to be filter by

![image](https://user-images.githubusercontent.com/29519901/36613214-d37aea78-18a6-11e8-9c35-1cc478eb3e7b.png)

**Comment by atl2017** [comment]
Justa another customer requested the same. The idea is an easy way to GoTo specific record

![image](https://user-images.githubusercontent.com/29519901/37000740-4af493ea-2092-11e8-9193-f196dce75796.png)

![image](https://user-images.githubusercontent.com/29519901/37000785-72860baa-2092-11e8-8b70-3c40ce35847e.png)

**Comment by nap2000** [comment]
ok cool.  SHouldn't be too hard.  I have a few urgent jobs at them moment will try and get back onto kontrolid issues soon.

**Comment by atl2017** [comment]
Great. If it is easy please include #189

**Comment by atl2017** [comment]
I recommend you. Thanks

**Comment by atl2017** [comment]
Any news about it?

**Comment by atl2017** [comment]
Maybe it could be another button like "Filter by ParKey"..


![image](https://user-images.githubusercontent.com/29519901/38398663-d71c5a70-390a-11e8-84b3-16c92646157f.png)

**Comment by atl2017** [comment]
Hi Neil, I need to llok into specific records to dowload pdf reports. It will be useful if you can include this feature soon. Yo wrote before that it couldn´t be hard.

**Comment by atl2017** [comment]
Hi Neil, still pending and another customer requested it. Thanks

**Comment by atl2017** [comment]
Neil, I just thinking that due to PDF Reports does not filter by subforms question but XLS report does, it could be useful to have this filter by parkey, because when necessary you can generate XLS reports (filtering by subforms question) and the manually goes to each parkey one by one.

**Comment by atl2017** [comment]
Now that you have include "You can now create filters such as: ${_hrk} = ‘abc 001’ and ${_device} = ‘1111111’"  we can use this as filter if Key is assigned. Should we consider to close this issue or we can consider include "record" as above?

**Comment by nap2000** [comment]
I have added the ability to use prikey in the advanced filter.  Ie ${prikey} = 1023

**Comment by atl2017** [comment]
tested Ok. Thanks!
