### ISSUE TITLE
FUTURE- BUG - Forward to server does not filter by advanced filter

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#200]
### Actual Behaviour: No matter I have included an advanced filter, all records were sent

![image](https://user-images.githubusercontent.com/29519901/36652683-2c280902-1a7e-11e8-8eca-997c12d129b6.png)

**Comment by atl2017** [comment]
@nap2000 Please mark a low priority or close without action. Not big deal. It is very specializad iisue

**Comment by nap2000** [comment]
I will leave this open one day when someone has 100, 000 records this will be important.
