### ISSUE TITLE
URGENT - Forward notifications is not working when data is imported

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#201]
### Actual Behaviour: Forwarding is not moving data when data is imported
![image](https://user-images.githubusercontent.com/29519901/36901335-cf1ecbf4-1df4-11e8-863a-658f8395e818.png)
![image](https://user-images.githubusercontent.com/29519901/36901340-d55dd712-1df4-11e8-9efb-f1711b64cc7b.png)
![image](https://user-images.githubusercontent.com/29519901/36901379-f1add034-1df4-11e8-8d3f-b09dc69cad61.png)

I need to move data updated by import because I have modified some columns and I need to rebuild all pdfs massively. Because a #99 solution is not available yet, a workaround is to simulate massive notification using email to an gmail account and use an add-on to automatically download attachments. I use this: https://digitalinspiration.com/product/save-gmail-to-google-drive.

In order to trigger those notifications with smap server to include all data (historical) is to move data from one account to another by using forward.

Yesterday was posible with production data but it fails when data were uploaded as import

### Server: www.kontrolid.com

1- In project Pruebas ALEXANDER 2 I upload attached form: R-0501. Both are used in source and destination.
2- I uploaded a zip with data0501old + media (39 MB)
3- In organisation: CLARO I created a project and uploaded the same form
4- In project Pruebas ALEXANDER 2 i create a notification wih forward

**Comment by nap2000** [comment]
Forwarding is not intended to be used with imported data and this will not be enabled. We will need to look at other solutions for your business need.

**Comment by atl2017** [comment]
Thanks Neil for your answer. I understood.  My root need can be solved with #99. Thanks
