### ISSUE TITLE
H2 - BUG - Either Browse result and Summary Report - Where set time zone?

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#205]
### Actual Behaviour: Time Zone in Browse results and Summary Report 

![image](https://user-images.githubusercontent.com/29519901/37108793-2844707a-2206-11e8-8c8e-0db882b0b642.png)

**Comment by nap2000** [comment]
All reports are currently in UTC/GMT.  Mainly this is because many Smap customers work across multiple timezones.  For the default timezone we could use the timezone of the browser for a report or the timezone of an organisation or leave it at UTC.   Possibly we could also add an option to the report generation to select a timezone which would override the default.

What are your thoughts

**Comment by atl2017** [comment]
I think you can use  timezone of an organisation as default because it is something already set as parameter.

**Comment by atl2017** [comment]
Is is possible to fix also this #267

**Comment by nap2000** [comment]
The data is retrieved using the API call /api/v1/data which will be widely used.  Currently the timezone is always set to UTC in the data returned.  If we default this to the organisation timezone then the timezone of the data for many queries will be affected.

**Comment by atl2017** [comment]
Hmm. Understood so please tag as wont fix and close.

**Comment by nap2000** [comment]
I've modified the API to take a parameter tz=xxxx.  If you don't specify a parameter as now then it will default to UTC.  I have also changed the browser in browse results so that it passes the timezone of the browser.

**Comment by atl2017** [comment]
Awesome.  Thanks a lot:

Tested with:
API : OK
Browse Results: OK
Browse Results ->Summary Report: OK
Browse Results: Download xls: OK
Analisis -> Export: OK

**Pending (Stil does not work):**  Export  and Export with Images as Zip
![image](https://user-images.githubusercontent.com/29519901/47555945-c7b41600-d8d2-11e8-937b-d6c2e7a223ed.png)

Reports as in: https://app.kontrolid.com/surveyKPI/action/u766c35f4-833f-4d55-98e2-c8320580ade9
![image](https://user-images.githubusercontent.com/29519901/47555982-e0243080-d8d2-11e8-9a01-407fd75082f0.png)

**Comment by atl2017** [comment]
Tested with:
API : OK
Browse Results: OK
Browse Results ->Summary Report: OK
Browse Results: Download xls: OK

_Reports as in: https://app.kontrolid.com/surveyKPI/action/u766c35f4-833f-4d55-98e2-c8320580ade9 still in UTC_

**Analisis -> Export: NOT OK** It worked some days ago.

**Comment by atl2017** [comment]
Thanks
