### ISSUE TITLE
ENHANCEMENT - Admin -> Download-> pdf template should include fields as by settings 

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#208]
### Expected Behaviour: - Admin -> Download-> pdf template should include fields as by settings 

![image](https://user-images.githubusercontent.com/29519901/37159914-ff49ffe8-22bc-11e8-93f7-97926dc1b137.png)

As in image above, process or downloading pdf templae should triggered the same as downloading pdf template in settings

**Comment by nap2000** [comment]
I'm not sure what the issue is here.  Can you be more specific?

**Comment by atl2017** [comment]
Sure. PDF template as is downloaded by  Admin -> Downloaded - PDF template is different (Without form field) from PDF Template that you download from button (with form fields). My advise is to include latter as answer from former. 

Is this way you can donwload PDF template easily and It is not necessary to open form and downoad from settings.

PDF template as I recommend (Admin -> Downloaded - PDF template)
![image](https://user-images.githubusercontent.com/29519901/37253172-1692089e-24fc-11e8-903a-9ae72c347779.png)

Current PDF Template (Admin -> Downloaded - PDF template):
![image](https://user-images.githubusercontent.com/29519901/37253187-4c535d8e-24fc-11e8-9aac-db2c245ddba4.png)

**Comment by atl2017** [comment]
Do you understand what is the difference between both reports? one has form fields and the other does not have.

**Comment by atl2017** [comment]
Was I clear?

**Comment by atl2017** [comment]
Neil check this [video](https://www.useloom.com/share/20d5a4e7c04d49118c87bdd49edde5b6) I explain with more details this.

**Comment by atl2017** [comment]
Not big deal
