### ISSUE TITLE
FUTURE - ENHANCEMENT - settings to disable projects

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#209]
### Expected Behaviour: Sometimes you have Projects that are not longer valid (deprecated) and you do not want to see  as part of list to choose because names could be confused and prevent wrong assignments.. It is a foolproof way. Of course another way is to change name.

![image](https://user-images.githubusercontent.com/29519901/37253257-64b60240-24fd-11e8-8b62-ae26bb719a27.png)

![image](https://user-images.githubusercontent.com/29519901/37253266-8a3d513a-24fd-11e8-8e68-93e59bc55806.png)

**Comment by atl2017** [comment]
@nap2000   Please mark a low priority or close without action. Not big deal

**Comment by nap2000** [comment]
I like the idea.  It will benefit some organisations significantly.
