### ISSUE TITLE
URGENT BUG - Delete data in Analysis is not working 

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#210]
### Actual Behaviour:

Delete Data is not working. Messages about process are displayed but data still remains

![image](https://user-images.githubusercontent.com/29519901/37261249-127ba96e-2569-11e8-9525-597aadb1ae1b.png)

### Form Name: Test Delete Data

Try to delete data and is not possible.

**Comment by atl2017** [comment]
Did you fixed it?  Right now is OK.

**Comment by atl2017** [comment]
Again!

**Comment by nap2000** [comment]
No I haven't looked at this yet.  Presumably the exact steps to reproduce the error have not yet been discovered.
