### ISSUE TITLE
BUG - 18.03 - Published Report - Embeded Images get narrow in Excel

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#212]
### Actual Behaviour
<img width="960" alt="2018-03-19 1" src="https://user-images.githubusercontent.com/29519901/37599725-67d8ad90-2b53-11e8-80bf-a453e000e597.png">

**Comment by nap2000** [comment]
Images will be sized to the size of the cell.   You can widen the column to change the image proportions.  I won't be changing this.
