### ISSUE TITLE
ENHANCEMENT - Include a widget that trigger a form

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#213]
### Expected Behaviour: Include a widget that trigger a new form. Sometimes forms are too big that it is necessary to split in different forms. So it would be interesting to have a widget that depends on condition trigger a form.

Widget could be like an image with parameters  survey_id = s_XXXXXX and when finished return to following question.  Triggered form would not be a subform, it is independent and just an easy way to redirect a flow of data collection.

Behaviour could be like saving form, open  a new form, filling out and return to former saved form, reopen, continue filling out and finish it.

**Comment by atl2017** [comment]
Could it be handle as explained [here launck collect from app doc:](https://docs.opendatakit.org/launch-collect-from-app/)

**Comment by nap2000** [comment]
Yes this is on the todo list.  It would also be useful in the situation where you had reference data for example you needed to link to an equipment ID.  However if that equipment had not been entered you would need to create by launching a new form and then get the ID back into the form you were working in.

**Comment by atl2017** [comment]
Yes you got it!  Any expected time to close this?

**Comment by atl2017** [comment]
Thanks a lot!

Pending that works with multiple forms. I mean More than one question as I wrote by email: [Video](https://drive.google.com/open?id=1UebGOYPBSfCNctO9pUQqSJ-DFu-J6k_H)
