### ISSUE TITLE
ENHANCEMENT - Group Task creation from existing data to include date question

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#214]
### Expected Behaviour: It could be useful to include as part of Group Task settings an option to include a date-time question to be used as Start Time to new task. Similar as Address parameters where you can include guidance dinamically. This new feature could help to automate follow-up systems and alerts based on data of surveys.

![image](https://user-images.githubusercontent.com/29519901/37660532-a582f358-2c20-11e8-8a94-89fd6b26753d.png)

![image](https://user-images.githubusercontent.com/29519901/37660777-34e32658-2c21-11e8-8797-8eb87a2dffde.png)

**Comment by atl2017** [comment]
I was thinking that:

1- End Time in Task is not so useful. Just Start.
2- If you can include more questions dinamically to set Tasks, you could provide an alternative to Tasks Template

**Comment by nap2000** [comment]
OK so this is start time and GPS coordinates?

**Comment by atl2017** [comment]
yes

**Comment by nap2000** [comment]
Anything is possible.   If you could describe in more detail how this would
work that will be useful.  Ie how the data will be used in completing the
task and managing tasks.  In where this happens if in the phone or on the
server

**Comment by atl2017** [comment]
Thanks for including
