### ISSUE TITLE
ENHANCEMENT - TRANSIFEX - Replace form by Repeat Icon text in editor

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#217]
### Actual Behaviour:
where can I replace this Icon text. "Form" is not adequeate, I think "Repeat" (Repetición) is more clear.

![image](https://user-images.githubusercontent.com/29519901/38421730-c26efdf4-396d-11e8-86de-cc3df46a8d19.png)

**Comment by nap2000** [comment]
Added to transifex.  English name is Sub - Form

**Comment by atl2017** [comment]
Thanks
