### ISSUE TITLE
TRANSIFEX - Editor - Tools -> Traslate  and default

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#224]
### Expected Behaviour:

![image](https://user-images.githubusercontent.com/29519901/38509221-e8550704-3be6-11e8-9426-676386293175.png)

**Comment by nap2000** [comment]
The translation for Default is currently "Default" so presumably that needs to be fixed in Transifex

**Comment by atl2017** [comment]
Oops ..fixed

**Comment by atl2017** [comment]
What about:

![image](https://user-images.githubusercontent.com/29519901/38730957-36050b62-3ede-11e8-9c3e-387063c9884c.png)

It was not traslated

**Comment by atl2017** [comment]
Tested OK
