### ISSUE TITLE
TRANSIFEX - Multimedia - image / language

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#225]
### Expected Behaviour:

![image](https://user-images.githubusercontent.com/29519901/38509381-587862b0-3be7-11e8-81ad-dad21cb661f9.png)

**Comment by nap2000** [comment]
The value "language" shown in the title bar is the name of the language for the form you are looking at.  In this case it has the default value of "language".  However if your form definition identifies a different language then that is what you will see.  Hence no translation should be applied to this.

**Comment by atl2017** [comment]
Could it be "Por Defecto" (Default?) or blank ? It looks like "spanglish"
