### ISSUE TITLE
BUG - Editor web - It is not possible to edit a question that refers to metadata

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#233]
### Actual Behaviour:

![image](https://user-images.githubusercontent.com/29519901/38761046-5befd9b2-3f45-11e8-8311-b435217859e8.png)

### Steps to reproduce the problem

See [video](https://www.useloom.com/share/ce48427b5de347a9be174a916d60c8c0)

**Comment by atl2017** [comment]
Neil,

Yo wrote "You can edit questions and if a question refers to a metadata item then as far as I know you can edit that reference."  In the example is not possible.

**Comment by nap2000** [comment]
OK Understood.   Should be fixed now.

**Comment by atl2017** [comment]
Tested OK
