### ISSUE TITLE
BUG - SQL error when try to download PDF report

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#238]
### Actual Behaviour:Following message is displayed. Form was uploaded and  1 record was input with FT

![image](https://user-images.githubusercontent.com/29519901/39087131-0d41b6aa-4562-11e8-8632-3972c21387bf.png)

Same error if I try to see as webform

![image](https://user-images.githubusercontent.com/29519901/39087143-6608cd96-4562-11e8-857c-7ac3037406b4.png)

### Steps to reproduce the problem

(Optional) If this is reproducible on a Smap hosted server then include

**Comment by nap2000** [comment]
Ok change made you should see a more informative error message now.

**Comment by atl2017** [comment]
Thanks. My mistake was that a include a comma(,) between two columns name in order to have extended labels. Separator was not necessary.

**Comment by atl2017** [comment]
Neil it happens again. I guess there is a bug when interprets multiple columns in the label as is:

![image](https://user-images.githubusercontent.com/29519901/39104827-c1797ce6-4677-11e8-8abb-0e21f4bf3ab0.png)

I tried either as comma-separated list or just space separated list. Both works fine in FT and  Analysis in the beginning 

![image](https://user-images.githubusercontent.com/29519901/39104864-f34c2228-4677-11e8-84b7-b8c8fafbd76c.png)

![image](https://user-images.githubusercontent.com/29519901/39104890-185aebbc-4678-11e8-923a-6541fc286724.png)

See steps to reproduce in following [Video](https://www.useloom.com/share/866137a74c4c4a93b2d7699fd9fec8af)

**Comment by nap2000** [comment]
Ah ok.  I did not know that you could have a comma separated list of labels.  Will look into it.

**Comment by nap2000** [comment]
Comma separated external labels should now be supported in webfoms, PDF and analysis graphs

**Comment by atl2017** [comment]
Thanks a lot. It works!

**Comment by atl2017** [comment]
Currently is not possible to change in editor:

![image](https://user-images.githubusercontent.com/29519901/39127650-3bf0edda-46cb-11e8-962a-425a3664a61d.png)

Do I need to raise as new issue?
