### ISSUE TITLE
BUG: link to image instead of image does not work

### ISSUE THREAD

**Issue by ztatu** [smap-consulting/smapserver#24]
### Actual Behaviour : Images at pdf: If you are exporting with a template and  specify a text field rather than an image field, first part of string (server name) is missed so link is not shown properly. Only:

![image](https://user-images.githubusercontent.com/29519901/28076187-77cfcb52-6623-11e7-8aed-16702f67f4b8.png)

### Steps to reproduce the problem: See attachment

[Balcon-902-1107170957 (1).pdf](https://github.com/smap-consulting/smapserver/files/1139396/Balcon-902-1107170957.1.pdf)
(Optional) If this is reproducible on a Smap hosted server then include

**Comment by nap2000** [comment]
I am writing the reference for the hyper link as the hyper link symbol to conserve space.

**Comment by ztatu** [comment]
Great solution. Tested OK.
