### ISSUE TITLE
HIGH BUG - start time has not been included in PDF reports

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#249]
### Actual Behaviour: It happens either standard or customised pdf reports

[widgets.pdf](https://github.com/smap-consulting/smapserver/files/1967183/widgets.pdf)
[Test.pdf](https://github.com/smap-consulting/smapserver/files/1967184/Test.pdf)
[survey.pdf](https://github.com/smap-consulting/smapserver/files/1967185/survey.pdf)

### Steps to reproduce the problem

(Optional) If this is reproducible on a Smap hosted server then include

**Comment by nap2000** [comment]
The preloads _start, _end are now available in the PDF.   Webforms still does not seem to allow calculations involving preloads.   Not sure why that is.

**Comment by atl2017** [comment]
1 - Confirmed. _start is only included if the name is not changed:

![image](https://user-images.githubusercontent.com/29519901/39572944-cbb3ad86-4e96-11e8-8ee1-32e6dbc35ac3.png)

2- Both are displayed NOT in local time. It should be in local time.

3- WebForms: Maybe you should check if the format you handle _start time is compatible with the way enketo supposed you should (as in datetime question)

**Comment by nap2000** [comment]
This should now be in local time

**Comment by atl2017** [comment]
Tested:  NOT OK

![image](https://user-images.githubusercontent.com/29519901/39625947-7c190274-4f65-11e8-9114-070eee247f87.png)

Organisation: Zarkman   Project:  TestAlex   Form: TestStart  

Downloading pdf for new records show +00 time

**Comment by atl2017** [comment]
Tested OK

![image](https://user-images.githubusercontent.com/29519901/39663475-bbaba1ce-5039-11e8-9cbf-bf3603502f4f.png)
