### ISSUE TITLE
BUG - WEB FORMS - Constraints are evaluated in optional questions

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#251]
### Actual Behaviour:

![image](https://user-images.githubusercontent.com/29519901/39572144-afbd9a36-4e93-11e8-8c55-4eb3bc02d369.png)

![image](https://user-images.githubusercontent.com/29519901/39572170-c70aec70-4e93-11e8-9077-6ac997d80995.png)

![image](https://user-images.githubusercontent.com/29519901/39572222-f6ec97ea-4e93-11e8-80cc-9e677428fb49.png)

### Steps to reproduce the problem

(Optional) If this is reproducible on a Smap hosted server then include

**Comment by nap2000** [comment]
Can you include in the issue a description of the problem.  Images may be useful to supplement this description.  However in this issue there is no statement of what the problem is.

**Comment by atl2017** [comment]
Ok. Sorry.

## Problem:  Constraints should apply only for non-empty answers in optional questions or in required questions. Currently with new web forms, constraints is being applied no matter question is empty. Example:    Whats is your age?  (Optional)  (Constraint: . <= 100)  if you leave blank will be OK or if you input 50 Ok but 105 must be an error. In web forms, if you leave blank it is marked as error

**Comment by atl2017** [comment]
Tested OK. Thanks
