### ISSUE TITLE
ENHANCEMENT - TASK GROUP - Use location from existing data as task´s location

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#254]
### Expected Behaviour:  Let define Task location in Task Group creation from existing data as collected location data

![image](https://user-images.githubusercontent.com/29519901/39708508-066cdcec-51dd-11e8-8cce-b948fa2e41a2.png)

As recently you have included Task´s Start from date question, you can close the cycle including location data.

**Comment by nap2000** [comment]
The location of the task is set from the existing data.   When you then look at your tasks on the phones you will see where it is supposed to take place.   Is that not what you want?

**Comment by atl2017** [comment]
Yes, you are right. Thanks a lot!

![image](https://user-images.githubusercontent.com/29519901/46257117-fe387580-c479-11e8-983b-a6eaaaaac93c.png)
