### ISSUE TITLE
H1 - TASK GROUP - Record Task Start Time as metadata 

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#255]
### Expected Behaviour:
I recommend include planned Task Start Date as metadata question in survey to compare scheduled vs. planned. I meant include Start and Start + duration as metadata like: _starttask and _endtask. So we later can compare _start vs _starttask

![image](https://user-images.githubusercontent.com/29519901/39708943-22809166-51de-11e8-90f6-54ed7c752e07.png)

**Comment by atl2017** [comment]
I have tested with different scenarios and I have not seen it working.

Below case is a simple acomplished task:

![image](https://user-images.githubusercontent.com/29519901/44116905-6696eb10-9fd7-11e8-9b11-2777dcaf2eb6.png)

Organisation: Zarkman
Project: TestTasks
Form: ToDo
TaskGroup  (Not based on previous results): SingleTasks

**Comment by nap2000** [comment]
I just tried this and _scheduled_start was recorded.  Perhaps this was fixed when another issue was closed.

**Comment by atl2017** [comment]
Now, I know what is happening. It only works when Task is accomplished by webform not FT. Please check image below: device not found = webform  device = number (IMEI) - Mobile device. In fact also start is not being recorded.

![image](https://user-images.githubusercontent.com/29519901/47099217-73d26e80-d1fa-11e8-838d-d1ac8d79087e.png)

**Comment by nap2000** [comment]
Good pick up.  The fix for this issue will be in fieldTask 5.8.

**Comment by atl2017** [comment]
Tested: OK

![image](https://user-images.githubusercontent.com/29519901/47779339-e34e6080-dcc6-11e8-8b81-8087745ed631.png)

Comments: When finish a simple test _start is record but when is based on results either start and device get lost:

![image](https://user-images.githubusercontent.com/29519901/47779946-5dcbb000-dcc8-11e8-8d56-b50ff480a48a.png)
