### ISSUE TITLE
HIGH - BUG - Dates with calculation does not save data properly

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#259]
### Actual Behaviour: Calculation when it is used as dynamic default in of date / datetime questions works fine to diaplay suggestion but if it is changed as normal, changes are displayed in FT but in server are saved calculate formula instead of new one. It happens ONLY when data is captured in FT. Using web forms works fine.

Example:
q1 as date question suggest today 2018-05-12  q3 as date question suggest q1 as default

Case 1 FT:  q1 = 2018-05-12  q3 suggest 2018-05-12 but it is changed to 2018-05-16. Saved data in q3: 2018-05-12
Case 1 WebForms: q1 = 2018-05-12  q3 suggest 2018-05-12 but it is changed to 2018-05-16. Saved data in q3: 2018-05-16

Case 2 FT:  q1 = suggest 2018-05-12  but it is changed to 2018-05-13 q3 suggest 2018-05-13 but it is changed to 2018-05-16. Saved data in q1: 2018-05-13   q3: 2018-05-13

![image](https://user-images.githubusercontent.com/29519901/39959101-46c4c1da-55d2-11e8-9983-87ca7fd31013.png)

Two first rows web forms:

![image](https://user-images.githubusercontent.com/29519901/39959087-19f49cb6-55d2-11e8-8309-f854a933bb22.png)

**Comment by nap2000** [comment]
It seems reasonable to me that the behaviour should be that once a manual entry has been entered for a question then the calculation should no longer be used.   I tested this with ODK and saw the same problem you describe.  I think this would best be raised as an issue with the ODK team.

**Comment by atl2017** [comment]
Thanks Neil,

May I ask you to please raise the issue with ODK?. I haven`t installed Aggregate server so due to situation is observed after saving data. I am not able to show them the problem.

**Comment by nap2000** [comment]
Does this: https://forum.opendatakit.org/t/is-it-possible-to-set-a-default-value-for-a-decimal-question-using-the-calculate-column/12141 address your issue?

**Comment by atl2017** [comment]
Thanks,

I included once(..) as was mention above in forum and works!

![image](https://user-images.githubusercontent.com/29519901/40095381-5e15c692-5891-11e8-91bc-9b814a183631.png)
