### ISSUE TITLE
BUG - WEB FORMS - Some styling <br/> does not work

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#270]
### Actual Behaviour: When some styling using concat are included Ex: concat('value:',${q1},'<br/'>) tag are considered as Text instead of HTML tag. But if the same tag is included as part of label it is OK. 
Both are Ok in FT. Situation only happens in Web Forms

![image](https://user-images.githubusercontent.com/29519901/40269519-6833601a-5b45-11e8-844c-902b70bb7735.png)

**Comment by nap2000** [comment]
Does this problem occur if you select the "preview in enketo" button on the odk xlsform translate page?

**Comment by atl2017** [comment]
Sorry I do not know what do you mean. Where to test?

**Comment by nap2000** [comment]
I was thinking of here: http://opendatakit.org/xiframe/

**Comment by atl2017** [comment]
It looks like this:

![image](https://user-images.githubusercontent.com/29519901/40284125-b50e53f8-5c4f-11e8-9c6e-3655a0dad601.png)

**Comment by nap2000** [comment]
Ok is that better or worse.  I'm trying to figure out if there is something in the Smap code or in the underlying enketo-core code that is causing the problem.   On initial inspection it seemed to be an enketo-core issue however if it works on the enketo web site then it would be something I am doing.

**Comment by atl2017** [comment]
Not big deal, because it means that we cannot include styling as part of concat but in labels, where it works fine.
