### ISSUE TITLE
TRANSIFEX - "Pages" style in settings still in english

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#271]
### Actual Behaviour:

![image](https://user-images.githubusercontent.com/29519901/40303552-cf3f24dc-5cb8-11e8-8748-eec8be0e5a2a.png)

**Comment by nap2000** [comment]
The Spanish translation is currently set to "Pages".

**Comment by atl2017** [comment]
Oops. Fixed. Thanks
