### ISSUE TITLE
HIGH BUG - WEB FORM - linked forms - consult data are affected if question have Uppercase and/or _

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#274]
### Actual Behaviour: Questions name must be in lowercase if it is intended to be used in Web Forms as source for linked forms

![image](https://user-images.githubusercontent.com/29519901/40523672-6f858c7a-5f9c-11e8-8936-27c0f5e174f2.png)

![image](https://user-images.githubusercontent.com/29519901/40523704-93872df4-5f9c-11e8-822c-7a1a11d9bfcc.png)

![image](https://user-images.githubusercontent.com/29519901/40523655-54d0377c-5f9c-11e8-937c-c655bbc64ba2.png)

**Comment by atl2017** [comment]
Hi Neil,

Now is HIGH because we have noticed and additional issue related. In web forms, if I get data with pulldata, question name have to be lowercase and cannot contain _

Organisation: Zarkman
Project: TestWebForms
Form: TestLinkedSelf

[TestLinkedSelf.xlsx](https://github.com/smap-consulting/smapserver/files/2238989/TestLinkedSelf.xlsx)

Steps to reproduced

1- See data recorded:
![image](https://user-images.githubusercontent.com/29519901/43368649-23e5c2f4-9326-11e8-91ad-e091ed309026.png)

2- Use form in webforms to recover data either record with id 1 or 2 (current data). Only it is possible to get information of q2c because it is lowercase and does not include _.  Q2c or q2_c DOES NOT get any data.

![image](https://user-images.githubusercontent.com/29519901/43368717-6433bf68-9327-11e8-85e0-860de6949cc0.png)

**Comment by atl2017** [comment]
Very important, due that the use _ as word separator is very common.

**Comment by martingpritchard** [comment]
Hi SMAP community, 
I believe this is also related to this issue.

When testing the solution to this issue, could you please also check that fields set in a SMAP web form using search() and pulldata() display correctly when displayed in a note type question. 

Currently, if the field name as an underscore in it AND the field value is set by pulldata() or search() AND the field value is later displayed in the form, then the value text displayed is **false**, not the actual value set.  At the backend, SMAP actually stores the correct values in the database tables.

Sample form attached. Fields sp_key_returned and t_sp_name display: false in fields n1 and n2

**Comment by nap2000** [comment]
Good pickup on the underscores in question names.  These were being converted into emphasis markers as in Markdown.  Should be right now.

**Comment by atl2017** [comment]
Tested *FAILED!* with:

Organisation: Zarkman
Project: TestWebForms
Form: TestLinkedSelf

[TestLinkedSelf.xlsx](https://github.com/smap-consulting/smapserver/files/2340849/TestLinkedSelf.xlsx)

Results are the same:

![image](https://user-images.githubusercontent.com/29519901/44924979-92e07400-ad12-11e8-8e79-3397fa190e8c.png)

**Comment by nap2000** [comment]
The update will be released satuday morning

**Comment by atl2017** [comment]
:+1:
