### ISSUE TITLE
QUICK? ENHANCEMENT - Change erase policy from 3 months to 1 month for deleted survey

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#282]
### Expected Behaviour: Change this policy from 3 months to 1 month for Kontrolid Server
 "When surveys are deleted the data is retained on the server and you can restore the survey to retrieve it. However from the 30th November, in order to save disk space, surveys that have been deleted for more than 3 months will be automatically erased after which you will not be able to recover the data. There will continue to be no limit to how long you can keep data from surveys that you have not deleted."

**Comment by nap2000** [comment]
Now set to 31 days for kontrolid
