### ISSUE TITLE
ENHANCEMENT - Move form(s) to a new project

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#283]
### Expected Behaviour: Most of the time you create and test forms in transitory projects until will it be ready to deploy. So you have to download form /pdf / and data if there are some valuable and to upload to a final project. It could be useful to have the chance to move a form from one project to another. Also to organize projects because of new needs.

Proposal a button and then a select_one box to choose from existing projects

![image](https://user-images.githubusercontent.com/29519901/40580543-ff9e2ca8-6105-11e8-8b9a-2e63e9613540.png)

**Comment by nap2000** [comment]
You can move a form to another project by selecting file | settings and then specify the project.

**Comment by atl2017** [comment]
What?  I didnít know and doing in the wrong way. Tested OK. Thanks a lot!
