### ISSUE TITLE
BUG - REPORTS - Roles are unassigned when you change one

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#299]
### Form Name: Test

1- There are two activated roles for above form: RolePrueba and test

![image](https://user-images.githubusercontent.com/29519901/41230675-5014e572-6d46-11e8-94b7-5dc5a5e5eb7f.png)

2- I created a report and use as filter role: test: (See below image that shows that role test is checked)
![image](https://user-images.githubusercontent.com/29519901/41230840-d520625a-6d46-11e8-91f4-4221289de5df.png)

![image](https://user-images.githubusercontent.com/29519901/41230596-fbb51808-6d45-11e8-8f6a-7acf32a352cc.png)

3- I edited the other role: RolePrueba adding row filtering. It could be anything. Just editing a role.
![image](https://user-images.githubusercontent.com/29519901/41231029-69cad8c2-6d47-11e8-8eef-c2b9889b68c7.png)

4- I was back to Reports and click to edit TestRol. What I see is thar role test is unchecked (see below)
![image](https://user-images.githubusercontent.com/29519901/41230626-14fde2d6-6d46-11e8-9e6e-a09fa013fc84.png)

**Comment by nap2000** [comment]
I haven't been able to reproduce this.  Can you clarify the steps.  May be easier if you write each step rather than using images

**Comment by atl2017** [comment]
I did my best. Steps are 1- 2- 3- and 4- and have images to show the results.

**Comment by atl2017** [comment]
Tested Ok. Did you fix it?
