### ISSUE TITLE
HELP - WEB FORM. What is wrong with csv file?

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#314]
### Actual Behaviour: An error message is displayed after loading form

![image](https://user-images.githubusercontent.com/29519901/41850249-7e1881e6-7849-11e8-8d68-961be4fd797d.png)

### Steps to reproduce the problem:  Just try to fill out this form by web.

(Optional) If this is reproducible on a Smap hosted server then include

**Comment by nap2000** [comment]
Its possibly related to this text:  Contactar al señ¯² Edgardo Alvarado

the power -2 part.  However I have not tested after fixing.  Note i think this text might occur at several locations in the file.

**Comment by atl2017** [comment]
It works. Thanks. 

What tool do you use to check csv files efficiently?

**Comment by atl2017** [comment]
Thanks.

On the other hand, Why the order and number of items to show are different in webforms and FT. What are the constraints in web forms. Below image, it i supposed that all items should be displayed and in the same order:

![image](https://user-images.githubusercontent.com/29519901/41855821-27665066-7859-11e8-8e0d-e548bed714d0.png)

**Comment by nap2000** [comment]
Not sure.  I think for webforms it just reads the choices in the order they exist in the file.  For fieldTask you can add an order by column and it will sort on that.  Probably needs to be looked at.

**Comment by atl2017** [comment]
Situation apparently is not with the order, situation is that Displayed items are a subset of all Items:

This is the first item:

![image](https://user-images.githubusercontent.com/29519901/41865880-11563776-7874-11e8-88c8-104483b2e4f3.png)

And it is displayed as:
![image](https://user-images.githubusercontent.com/29519901/41865921-3dc0594a-7874-11e8-848c-23cfb493e397.png)
