### ISSUE TITLE
BUG OR ENHANCEMENT - When a form is replaced Pulldata settings get lost

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#315]
### Actual Behaviour:
BEFORE:
![image](https://user-images.githubusercontent.com/29519901/42050299-1ff4cb88-7ace-11e8-9a24-4c5e76801819.png)
AFTER FORM WAS REPLACED:
![image](https://user-images.githubusercontent.com/29519901/42050223-f305b4de-7acd-11e8-814b-4e986de8c452.png)

**Comment by nap2000** [comment]
Pulldata settings are now saved.  Note I have also simplified the dialog and clarified the usage of this feature.  It should only be used when you are doing pulldata requests on data in repeating groups.  Refer to slide 13 and on in here https://drive.google.com/file/d/0B5_SmpWlQYxvbEJWc1UwYkV4Z3M/view?usp=sharing

**Comment by atl2017** [comment]
Great!

**Comment by atl2017** [comment]
I think I made a mistake with former tests. I realized pulldata_repeat settings are now specified at settings.

Thanks
