### ISSUE TITLE
BUG  - PDF report crashes when use static choices with external files

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#319]
### Actual Behaviour: I can use font color at choices and it works fine in FT, but PDF report crashed

![image](https://user-images.githubusercontent.com/29519901/42135903-9ce6a166-7d17-11e8-9b12-cf2df348e5e8.png)

![image](https://user-images.githubusercontent.com/29519901/42135867-ed5783aa-7d16-11e8-9a54-16d0374850c6.png)

**Comment by atl2017** [comment]
When I delete html tag another error was displayed. I does not accept static choice 0

![image](https://user-images.githubusercontent.com/29519901/42136358-3f835c8c-7d1f-11e8-9e62-e24c80c319fc.png)

**Comment by atl2017** [comment]
It works for static choice, but 0 choice must be last:

![image](https://user-images.githubusercontent.com/29519901/42136600-3798edde-7d24-11e8-885f-0a4cf3501f59.png)


![image](https://user-images.githubusercontent.com/29519901/42136588-07dc6c6a-7d24-11e8-8d02-340111d2ecc7.png)

**Comment by atl2017** [comment]
It works inclusive with html tags in choices:

![image](https://user-images.githubusercontent.com/29519901/42136947-bc0934d4-7d29-11e8-84c7-0a12f71991c4.png)

The only situation is that the static label have to be the last (not the first as I believe)

**Comment by atl2017** [comment]
I made a mistake when testing. 

It does not work for standard PDF. It crashes as I reported at the beginning either for html tags and for static choice.

**Comment by nap2000** [comment]
I have made an update to make use of the HTML when showing choices in a default PDF.  This works with choices from a CSV file.  Refer to the form "csv colours" in the "default" project of the zarkman organisation.

However that is not the problem you are reporting.  Possibly its something to do with the "in" match you are using?  Anyway can you provide information on how to reproduce this problem.

**Comment by atl2017** [comment]
Thanks

organisation: ZARKMAN
Project: TestAlex
Form: 2 - SalidaAlmacen - 40 Items Max

If you need to introduce some record just use SECUENCIA: 144447, 144448, 144449, 144451, 144452, 144453. The first select_multiple you have to check all and the second none.

Currently, trying to download pdf report crashes and display the following message:

![image](https://user-images.githubusercontent.com/29519901/42161181-89f2f0a2-7dbf-11e8-99dc-b449e22fa23f.png)

it is related with this choice:
![image](https://user-images.githubusercontent.com/29519901/42161192-9b3e45f0-7dbf-11e8-861f-c4d3f2193b66.png)

**Comment by atl2017** [comment]
I recommend this. Thanks for your help

**Comment by atl2017** [comment]
Neil,

I have create a new version or csv colours. Refer to the form "csv colours2" in the "default" project of the zarkman organisation. I have included a static choice:

![image](https://user-images.githubusercontent.com/29519901/42191941-3fd02f96-7e2b-11e8-837f-3e7b12b06934.png)

Report crashes like problem reported above

![image](https://user-images.githubusercontent.com/29519901/42191867-e28a75c6-7e2a-11e8-9eeb-234453d90df2.png)

**Comment by atl2017** [comment]
Also I created another version: csv colours3 with the html tags in the static label

![image](https://user-images.githubusercontent.com/29519901/42192218-182b9618-7e2d-11e8-8afa-035fd07db7f7.png)

PDF report crashes with different error:
![image](https://user-images.githubusercontent.com/29519901/42192258-54748800-7e2d-11e8-88fa-7f372cbe1352.png)

PRIORITY is to fix about static choices more than html tags. Thanks

**Comment by atl2017** [comment]
Hi Neil, 

Now is low priority.

I decided to redesign form to avoid static choice while you can fix it. Thanks for your time.

**Comment by nap2000** [comment]
OK yep.  This static choices feature does not seem very important to me.  So hardly seems worth the worry of making it woking with html markup.  However if you get a business need then raise the priority back up.

**Comment by atl2017** [comment]
Thanks again. I close without fixing.

**Comment by nap2000** [comment]
Ok i will fix it!

Le mar. 3 juil. 2018 13:33, Alexander Torrado <notifications@github.com> a
écrit :

**Comment by atl2017** [comment]
Hi Neil,

One of my customers cloned a form that works fine whed PDF is downloaded, but clone does not. PDF crashes:
![image](https://user-images.githubusercontent.com/29519901/44309636-57978a00-a38f-11e8-82f6-3d88e1fe980e.png)

Source:
Organisation: GRUPO COLBA
Project: LOGISTICA
Form: SalidaAlmacen - 40 Items Max
PDFs are downloaded fine
It contains the same that is supposed to affect: Both static choice + htmal tags in choices labels
![image](https://user-images.githubusercontent.com/29519901/44309695-0c31ab80-a390-11e8-99d0-1c6e3e655bf5.png)

Clone:
Organisation: GRUPO COLBA
Project: IMPUESTO
Form: ENTRADA
PDF crashes

**Comment by atl2017** [comment]
Tested Ok. Thanks a lot
