### ISSUE TITLE
ENHANCEMENT - As part of AI web services consider TTS

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#321]
### Expected Behaviour. Have access to a  TTS (Text to Speech) service like https://aws.amazon.com/polly/what-is-text-to-speech/
in order to add value for some questions ie type acknowledge and to play a dynamic sound to confirm. If it is static of course we can use audio as media.

**Comment by nap2000** [comment]
Is this a question for odk?

**Comment by atl2017** [comment]
Not sure. I was thinking about your recent entry at yout blog:

![image](https://user-images.githubusercontent.com/29519901/42138586-56b51528-7d45-11e8-813d-45a8447de9b3.png)

**Comment by nap2000** [comment]
Ok.  maybe not a priority.   But it would be good to use more AWS services.
