### ISSUE TITLE
TRANSIFEX and Better message - Group Task when filter is not able

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#324]
### Actual Behaviour: Following message is displayed when filtering is not OK

![image](https://user-images.githubusercontent.com/29519901/42291395-f0cfafe0-7f90-11e8-8239-b8411ec71cf1.png)

![image](https://user-images.githubusercontent.com/29519901/42291419-1323aa88-7f91-11e8-9d81-4d6c6dce14e8.png)

After fixing in the same screen a new error is displayed:

![image](https://user-images.githubusercontent.com/29519901/42291460-61ee02a8-7f91-11e8-9a91-4c3844b75731.png)

### Steps to reproduce the problem

Try to filter tasks when value is not able.

**Comment by nap2000** [comment]
Can you provide the steps to reproduce this problem including the filter value that you entered and why it was invalid.

**Comment by atl2017** [comment]
Sorry. I tried but I could not reproduce steps.

When it happens next I will reopen.
