### ISSUE TITLE
TRANSIFEX - Error message when label is missing

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#325]
### Actual Behaviour:

![image](https://user-images.githubusercontent.com/29519901/43116832-5396bd60-8ecf-11e8-8861-b08014fba61e.png)

### Steps to reproduce the problem

Upload a form with a question without label

**Comment by nap2000** [comment]
This is an error from the ODK javarosa library.  OK i could check for missing labels however at the moment I'm not sure when to do this. Sometimes a missing label is fine which is why I am leaving to java rosa

**Comment by atl2017** [comment]
Understood
