### ISSUE TITLE
TRANSIFEX - Error when used indexed-repeat

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#326]
### Actual Behaviour:
![image](https://user-images.githubusercontent.com/29519901/43136289-dbf5ef76-8f0d-11e8-9f5c-9615218e3f5d.png)

### Steps to reproduce the problem

Use indexed repeat and switch repetion group and question

**Comment by nap2000** [comment]
This is an error message from the ODK JavaRosa library.  I won't add translations to that.

**Comment by atl2017** [comment]
Understood
