### ISSUE TITLE
H1 - BUG - When a record is marked as bad in main subforms remain marked as not bad

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#327]
### Steps to reproduce the problem

(Optional) If this is reproducible on a Smap hosted server then include

### Form Name: 

1- SOLICITUD DE INVENTARIOS
2 - APROBACION SOLICITUD DE INVENTARIO

![image](https://user-images.githubusercontent.com/29519901/43155159-49f7617a-8f3c-11e8-9dfd-437cd2fe4a02.png)

Records in subforms are duplicated with former and new data:

![image](https://user-images.githubusercontent.com/29519901/43155252-7e8de152-8f3c-11e8-9a26-fd90f4f0f5ca.png)

**Comment by nap2000** [comment]
great can you describes the steps to reproduce this issue.

**Comment by atl2017** [comment]
In order to reproduce the issue I have created a new form:

Organisation: Zarkman
Project: Test Meeting Minute
Form1: Test Marked as Bad
Form2: Test Marked as Bad 2 (Grouped with above Form1)
Task Group: Test  based on previous result. It use question Email to get email where to send email task.

Step 1- Fill-out Form1. q1  with any text. q3 (Email): Introduce any valid email to receive notification (Email task)
Step 2- Fill-out web form sent by Email and change some data 
Step 3- Check Analysis and see differences.

After task completion you can observed that main is marked as bad but subform do not.

![image](https://user-images.githubusercontent.com/29519901/43176568-d8e999be-8f89-11e8-98a1-f567d8473b45.png)

![image](https://user-images.githubusercontent.com/29519901/43176597-077dab58-8f8a-11e8-961c-9634d9b16725.png)

When the edition happens directly as "Edit in web form" both main and subform are marked as bad (Expected result):

![image](https://user-images.githubusercontent.com/29519901/43176696-792713d4-8f8a-11e8-9153-292bbe997c62.png)

![image](https://user-images.githubusercontent.com/29519901/43176709-9000e242-8f8a-11e8-93ec-66e006f3b71c.png)

**Comment by atl2017** [comment]
Pending: You wrote me by skype ""There is a setting you can do in the form to replace sub forms" . I do not know how.

**Comment by nap2000** [comment]
Use the parameter:     merge=yes

This replace the merge repeat entries. 
Example:  You have 2 repeat entries, in your task you update one and add one more.  The result will be 3 entries as you submitted from the task.  An identical result to the old behaviour.

**Comment by atl2017** [comment]
Sorry Neil, but I haven´t had with this. I used merge=yes in one or both forms and nothing happens:

![image](https://user-images.githubusercontent.com/29519901/43344688-400cf2c6-91b0-11e8-8b16-356ca2aff1c5.png)

Could you please check by yourself and modify forms if necessary to show how to do it. These forms are for testing. Do not worry to do whatever is necessary.

Organisation: Zarkman
Project: Test Meeting Minute
Form1: Test Marked as Bad
Form2: Test Marked as Bad 2 (Grouped with above Form1)
Task Group: Test based on previous result. It use question Email to get email where to send email task.

Step 1- Fill-out Form1. q1 with any text. q3 (Email): Introduce any valid email to receive notification (Email task)
Step 2- Fill-out web form sent by Email and change some data
Step 3- Check Analysis and see differences.

After task completion you can observed that main is marked as bad but subform do not.

**Comment by nap2000** [comment]
ok.  It looks like if you add the parameter merge=yes via the online editor it is not applied.  Adding it via an xlsForm does seem to work.

**Comment by atl2017** [comment]
Neil, maybe bug is different and is related as behaviour of merge.

I have created another example in other project.

organisation: Zarkman
project: Test merge in repeats
forms: 1 - FT-CM-002 LISTADO DE PREDIOS HABILITADOS
2- FT-CM-002 LISTADO DE PREDIOS HABILITADOS

Both form are practical equal, except (Form 2) row 14 and 15 does not have calculation in dates. Form 1 uses calculation to use dynamic defaults.

Form 1 & 2 just select a week period and select multiple items from external file. It is like an activation system. 

Because constraints in web forms in this type of forms using select from external and then using a repeat, I am not able to edit data to add or erase items. So I decided to model with a task group  from existing data and assigned to an user that uses as a new survey a clone form (Form 2) that share data with Form 1. In this model I can edit data in FT but at smap server behaviour is not as I expected in subforms: merge=yes not only does not replace former data with new ones but add duplicates values.

Main table:
![image](https://user-images.githubusercontent.com/29519901/43423066-f92f53a4-9410-11e8-8797-e41c578f5f2e.png)
 
Subform:
![image](https://user-images.githubusercontent.com/29519901/43423151-38acd614-9411-11e8-8f16-e8e1dff0ca51.png)

Step to reproduce:

1.  Delete all data to start from zero.
2.  Edit Task and assign yourself to tasks
3.  Use 1 - FT-CM-002 LISTADO DE PREDIOS HABILITADOS at FT and just select only first item 4A0010
Data should looks like this:
Main
![image](https://user-images.githubusercontent.com/29519901/43423544-59e7e96c-9412-11e8-962c-43b7d6035669.png)
Subform: Predios
![image](https://user-images.githubusercontent.com/29519901/43423510-445a8d8e-9412-11e8-89d2-a189729fd372.png)
4- A task have to be generated to your user to be accomplish in FT.  Add a new item ie  4A0020. Send data to server.

Now data looks like this:
Main
![image](https://user-images.githubusercontent.com/29519901/43423837-15f90820-9413-11e8-9086-34765e92bfbd.png)
Subform: Predios
![image](https://user-images.githubusercontent.com/29519901/43423955-792a7bd6-9413-11e8-866c-f004ef2e74d9.png)
In fact, results for this example haven´t recorded 4A0020, and I do not why.

Feel free to erase data, upload, replace forms etc to understand situation. Thanks for your help. Now I need this with highest priority.

Thanks for your help

**Comment by atl2017** [comment]
Yes I load all forms as XLS Forms.

**Comment by atl2017** [comment]
I am pending of this high priority issue. If you need more testing I can help

**Comment by nap2000** [comment]
Unfortunately I cannot reproduce the problem.

It is not doing the merge in the case of the example you cite because the repeating group in 2 - FT-CM-002 LISTADO DE PREDIOS HABILITADOS does not have the parameter "merge=yes".  Hence the form has not been set to merge.

You need to set the merge=yes in the parameter of an xlsForm.  I have a fix ready to go that will allow you to set the parameter in online forms but that is not really the issue that has been raised.

**Comment by atl2017** [comment]
I tested before setting merge=yes in both forms using xlsform and in one form. Both cases I use xlsform with your instructions.

**Comment by nap2000** [comment]
I think you may have misunderstood the requirement.   There are no parameters set at all for the begin repeat in the xls form 2 - FT-CM-002 LISTADO DE PREDIOS HABILITADOS  that I downloaded from your project.  At least I could not see one.   This functionality is deployed at several sites and I haven't had a problem with it.  It is documented in the Survey Edit Reference file.  https://drive.google.com/drive/u/0/folders/0B5_SmpWlQYxvNExwSFV5X051Yjg

**Comment by nap2000** [comment]
Check in the parameters section of the file I referenced in the previous comment.   This parameter "merge=yes" has to be applied to the subform that you want to merge.

**Comment by nap2000** [comment]
I have updated your server to add the setting of merge and reference parameters from the online editor.  Previously these were added to the question so it looked like it worked, however they were not applied to the sub form definition which is where they were needed.  You should not be able to edit your surveys to add "merge=yes" to the subforms that you want to be merged rather than appended.

**Comment by atl2017** [comment]
Thanks a lot.

Finally I found out root cause: I have used key at main with policy = merge. I changed it to None:

![image](https://user-images.githubusercontent.com/29519901/43522647-97f4b17e-955f-11e8-9fff-2b9f7bb142de.png)
and voilá!

![image](https://user-images.githubusercontent.com/29519901/43522697-c1d7dbf6-955f-11e8-9751-506d61ad3b69.png)

**Comment by atl2017** [comment]
Neil, this situation is really frustrating.

Again is not working and I do not why.

![image](https://user-images.githubusercontent.com/29519901/43560778-bb5b8d5c-95d9-11e8-841f-c8cac725a061.png)

I have downloaded and uploaded again form you did with merge=yes adn Now is not working. I also deleted Key in main and upload in additional Project with the same result.

Organisation: Zarkman 
Project: Test Merge in Repeats
Forms: test upload  and test upload clone
Task Group: Test 10
![image](https://user-images.githubusercontent.com/29519901/43560995-96411842-95da-11e8-9d22-28d3d6b5bfd2.png)

Please help me with this matter. Feel free to edit forms and Task group

**Comment by atl2017** [comment]
My hyphothesis is that issue is related with Email Task and the link: https://app.kontrolid.com/webForm/action/ xxxxxxxx  because if I edit in webform directly "merge" policy works!

**Comment by atl2017** [comment]
### Steps to reproduce issue
### Organisation: SERACIS
1. I have created a new project
### Project: Pruebas CONTROL DE INVENTARIO v2
2. I have uploaded following form: 
[1- SOLICITUD DE INVENTARIOS.xlsx](https://github.com/smap-consulting/smapserver/files/2253767/1-.SOLICITUD.DE.INVENTARIOS.xlsx)

3. I have uploaded following form and group with above just to share data tables
[2 - APROBACION SOLICITUD DE INVENTARIO.xlsx](https://github.com/smap-consulting/smapserver/files/2253772/2.-.APROBACION.SOLICITUD.DE.INVENTARIO.xlsx)
4. I  Created a Task group from existing data (Email Task):
![image](https://user-images.githubusercontent.com/29519901/43588927-34ffadb0-9633-11e8-9a8d-305a6e5f954d.png)

5. Email Tasks were created:
![image](https://user-images.githubusercontent.com/29519901/43589005-6cb0af20-9633-11e8-9d03-cee79583cf30.png)

6.  Email with task were receive by Zoho mail:
![image](https://user-images.githubusercontent.com/29519901/43589119-a9bc2822-9633-11e8-81e0-b61e5514b2d0.png)

7.  After clicking link:
![image](https://user-images.githubusercontent.com/29519901/43589211-dc36b4f2-9633-11e8-8a7e-76b25452db57.png)
Error is displayed:
![image](https://user-images.githubusercontent.com/29519901/43589304-07f34876-9634-11e8-95a0-a8e35a6c3632.png)

### Second Example:

### Organisation: Zarkman
###Project: Test Merge in Repeats
###Form: 
1. test upload (is the same as you upload before) 
[test upload.xlsx](https://github.com/smap-consulting/smapserver/files/2253827/test.upload.xlsx)
Form2: test upload clone. Same as before plus one acknowledge  and grouped with it
[test upload clone.xlsx](https://github.com/smap-consulting/smapserver/files/2253830/test.upload.clone.xlsx)

2. I have created a Task Group: (Email Task)
![image](https://user-images.githubusercontent.com/29519901/43589844-3151e4d8-9635-11e8-90a8-1fc1fddd66cd.png)
3. After completing tasks subforms does not merge records in subforms, only in main table:
![image](https://user-images.githubusercontent.com/29519901/43589946-6fb9f31e-9635-11e8-82a9-3e391c45a887.png)
![image](https://user-images.githubusercontent.com/29519901/43589982-84391a9a-9635-11e8-86d1-9fba3b7ca419.png)

### Expected Behaviour:  It must be the same in Email Tasks as current is when you edit directly as webforms

After I edited record:
![image](https://user-images.githubusercontent.com/29519901/43590198-1017410e-9636-11e8-9b72-a5d6954bb91b.png)

Records in subforms were merge and replaced:
![image](https://user-images.githubusercontent.com/29519901/43590084-d1c01b38-9635-11e8-9558-77417d25e1ab.png)

**Comment by nap2000** [comment]
The steps seem to be missing something.  Why were the 4 email tasks created.  There was not data in the source survey.

**Comment by atl2017** [comment]
Yes there are data for examples above. Fro organisation SERACIS do not confuse with 2 projects with similar names. It is V2:

![image](https://user-images.githubusercontent.com/29519901/43591905-0050d182-963a-11e8-9622-9cd6fe355d50.png)

But in fact I found out a new issue. When I edit Group Task, it is displayed as belonging to the other project not V2:

![image](https://user-images.githubusercontent.com/29519901/43591997-38b091ca-963a-11e8-8c11-122374c071d3.png)

**Comment by nap2000** [comment]
Sorry I'm following the steps.  Create a new project load the forms.  How were the initial results added.  Presumably I just run that first form 4 times

**Comment by nap2000** [comment]
I'm stuck.  Trying to run the first form 4 times.  Its seems to require a bar code to be read.

**Comment by atl2017** [comment]
![a i a centroempresarialbelenusporteria4692](https://user-images.githubusercontent.com/29519901/43594151-1eeece3c-963f-11e8-9397-be53e57047ea.png)
![a i a centroempresarialbelenusrondero4729](https://user-images.githubusercontent.com/29519901/43594152-1f0eae28-963f-11e8-85a9-9142a52f5ee6.png)

I thought it has as default (to skyp): A.I.A./Centro Empresarial Belenus/_/Porteria _/4692

**Comment by nap2000** [comment]
Ah the problem is my user name is not recognised.   This is hard work.  It would be easier if I could start from a project that was already populated.

**Comment by atl2017** [comment]
Sorry. Use as metadata username: Julio Cesar Jimenez Cortes

**Comment by nap2000** [comment]
I encountered the authorisation error.  This is because I do not one of the roles that the 2nd form requires.   

For email tasks I think it should not apply the check on roles when processing a submisison.  That is given that we have sent a form to someone to fill in anonymously.  I can make an update to make this the actual behaviour.

**Comment by atl2017** [comment]
Grest. Hard work but it was the only way you can find hidden issues. Next is to find out merge issues.

**Comment by nap2000** [comment]
Ok Update will be put out overnight along with language updates.

**Comment by atl2017** [comment]
Ok. I saw your test and find that you can reproduce "merge=yes" problem. 

Expected behaviour: parkey: 1 becomes red and bad reason merged with 2

![image](https://user-images.githubusercontent.com/29519901/43596673-961d1ad0-9645-11e8-9f1d-02db9050dd65.png)

**Comment by atl2017** [comment]
Authorisation error fixed. Tested OK.
