### ISSUE TITLE
BUG - Answers are not shown in standard PDF report since 2 weeks ago

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#329]
### Actual Behaviour
[Serie Juan Juan 2_3.pdf](https://github.com/smap-consulting/smapserver/files/2226222/Serie.Juan.Juan.2_3.pdf)

### Steps to reproduce the problem

(Optional) If this is reproducible on a Smap hosted server then include

### Form Name: Control Asistencia

Check pdf report as above and see the answers related to names. Compare with records in analysis. Situation had happened since last two weeks ago, after server update.

![image](https://user-images.githubusercontent.com/29519901/43177390-ac10bae0-8f8d-11e8-9b4c-d35230b71482.png)

**Comment by nap2000** [comment]
This bug was introduced when the change was made to support colours in choice columns.  It worked if there was a colour setting but unfortunately if there was no colours the choice was not displayed.  Should be fixed now.

**Comment by atl2017** [comment]
tested Ok. 

Thanks
