### ISSUE TITLE
ENHACEMENT - API access to tables other than main (subforms)

### ISSUE THREAD

**Issue by ztatu** [smap-consulting/smapserver#33]
### Actual Behaviour Available services as mention in [https://www.smap.com.au/apiHelp.shtml#services](https://www.smap.com.au/apiHelp.shtml#services)
I see that  ..server/api/v1/data/XXXX )only get data from MAIN table. If there are subforms, data are not displayed.

**Comment by ztatu** [comment]
@nap2000 you wrote before:  This service is based on the one made available by Kobo which I don't believe allows access to sub forms.  I would need to extend it.

regards

Neil

**Comment by ztatu** [comment]
@nap2000 I recommend you this issue. I have moved forward with customer´s integration and it should be necessary soon.

Regards

**Comment by ztatu** [comment]
Tested Ok. What I still pending could be the chance to filter start but with parkey instead of prikey. Maybe a new filter call "start_parkey".

**Comment by nap2000** [comment]
done

**Comment by ztatu** [comment]
Excellent solution. Thanks!
