### ISSUE TITLE
HIGH - BUG - EMAIL TASKS link and unsubscribe are null

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#331]
### Actual Behaviour: Email Tasks are being created with null link:
![image](https://user-images.githubusercontent.com/29519901/43235735-62d7ff5e-9047-11e8-93fa-a611916843df.png)

### Steps to reproduce the problem

(Optional) If this is reproducible on a Smap hosted server then include

**Comment by nap2000** [comment]
Should be fixed now however I am not receiving emails from the server.  They seem to be sent alright.  Is there a problem with the email gateway?

**Comment by nap2000** [comment]
Ah it is being marked as spam!  You will need to look into that with your email gateway.

**Comment by atl2017** [comment]
tested OK. 

I have had 0 spam report:

![image](https://user-images.githubusercontent.com/29519901/43262911-591550e2-90a7-11e8-8410-c1a1ad882dd7.png)

**Comment by nap2000** [comment]
ok hopefully it is just me. gmail put them in my spam folder.
