### ISSUE TITLE
ENHANCEMENT - Tasks - By Default peridod should be All

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#333]
### Actual Behaviour: By default period is Week

![image](https://user-images.githubusercontent.com/29519901/43329407-e1fd7b62-9185-11e8-816a-c58555b9cdd1.png)

**Comment by nap2000** [comment]
I disagree.  If you have 10,000 tasks then period = all will result in a delay in showing tasks when most people only want to see what is happening recently.

**Comment by atl2017** [comment]
Ok. You are right.
