### ISSUE TITLE
Smap email notification issues

### ISSUE THREAD

**Issue by tymiles003** [smap-consulting/smapserver#339]
### Steps to reproduce the problem:  Uploaded the task template with the the email addresses added and received the email notification with the wrong address.

(Optional) If this is reproducible on a Smap hosted server then include

**Comment by nap2000** [comment]
Can you provide the actual steps you took to get the email sent.  For example is this a notification or a task?  

It would seem its not getting the correct hostname for your installation but it would help if I could work out which code was attempting to determine this host name.
