### ISSUE TITLE
HIGH - BUG - Emails Tasks block Notification by Email 

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#340]
### Expected Behaviour:
Notification does not show any error, so emails should be sent

### Actual Behaviour:
4 notifications have been programmed but only task email have been sent ( I haven´t tested but task email cancel notifications?)
![image](https://user-images.githubusercontent.com/29519901/43400868-7366f1c8-93d4-11e8-8989-88e4ace9e26e.png)

![image](https://user-images.githubusercontent.com/29519901/43400946-a0cfe55c-93d4-11e8-88ce-0e4ab7011dd0.png)

### Steps to reproduce the problem

Just click and do the following task:
Para su revisi?n AT-ALMACENES EXITO SAN BLAS-Registro-SUP-3007180845 y envio al cliente si es necesario. 

https://app.kontrolid.com/webForm/action/u4898e981-eeb9-4759-b230-b8c2fd5e29cf 

1- Just sign:
![image](https://user-images.githubusercontent.com/29519901/43401226-2e8d5cee-93d5-11e8-9231-1c2957de29ed.png)
2- and check ('Si) and introduce your email
![image](https://user-images.githubusercontent.com/29519901/43401243-3e79c868-93d5-11e8-806c-a9eec7b8bb68.png)
3- Send the form. Check for your notification

**Comment by nap2000** [comment]
The description of this issue is incorrect.  I have tested with other forms and notifications and tasks are both sent.  So presumably there is some problem with this specific survey.

**Comment by atl2017** [comment]
Ok. Understood.
