### ISSUE TITLE
BUG - When main record is marked as bad subforms should be marked as bad too

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#348]
### Steps to reproduce the problem

(Optional) If this is reproducible on a Smap hosted server then include

### Form Name: 2.-.APROBACION.SOLICITUD.DE.INVENTARIO
main table:
![image](https://user-images.githubusercontent.com/29519901/43643468-fbcfe3e8-96f0-11e8-8d67-4961cbd134e6.png)
subform: PRODUCTOS
![image](https://user-images.githubusercontent.com/29519901/43643514-1ee93fbe-96f1-11e8-9e75-e11c2527ef24.png)
API consult:
![image](https://user-images.githubusercontent.com/29519901/43643581-598db41a-96f1-11e8-836a-eb5fc2a7a86f.png)

**Comment by atl2017** [comment]
Did you fix it, already?  Now it is OK:

![image](https://user-images.githubusercontent.com/29519901/43676652-b26c8448-97ba-11e8-83f8-be54b9754bbe.png)

**Comment by nap2000** [comment]
ah yes sorry I thought I had marked released.

Le sam. 4 août 2018 à 14:48, Alexander Torrado <notifications@github.com> a
écrit :

**Comment by atl2017** [comment]
Tested Ok. Thanks
