### ISSUE TITLE
HIGH - BUG Hyperlink to image in customised pdf is not working

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#354]
### Form Name: TestFoto

Just download pdf and check.

![image](https://user-images.githubusercontent.com/29519901/44298991-1631ac80-a2b3-11e8-81ef-df18f443e1be.png)

**Comment by nap2000** [comment]
This problem manifested itself when the width of the field allocated to the hyperlink is large.  The size of the hyperlink that gets written is only the width of a character so generally to control the position you would keep the width of these fields to about that size.  However it has now been fixed so you can use large fields for hyper links.

**Comment by atl2017** [comment]
Tested Ok. Thanks a lot

![image](https://user-images.githubusercontent.com/29519901/44309901-2a4cdb00-a393-11e8-8011-2c22a09ce893.png)
