### ISSUE TITLE
ENHANCEMENT - Shared Resources : Include a filter to know where file is used

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#358]
### Expected Behaviour: Sometimes it is necessary to do some cleaning and erase csv and multimedia that are not longer used. But it is hard to know where a file is used.

Proposal: To include a button with action: List where is used

![image](https://user-images.githubusercontent.com/29519901/44590286-6790de80-a780-11e8-8485-33909fb8c13f.png)

**Comment by nap2000** [comment]
Ok.  I agree though more work needs to happen on shared resources.  Being able to track changes to files would also be good as currently people can replace a good csv file with a bad one and their is no log about that.
