### ISSUE TITLE
search('linked_self') does not work in SMAP web forms

### ISSUE THREAD

**Issue by martingpritchard** [smap-consulting/smapserver#360]
### Component fieldTask or SmapServer
SmapServer
### Version
18.07
### Expected Behaviour
select_one combined with search('linked_self') allows user to search for data already entered using this form. 
### Actual Behaviour
No data returned and shown in the search list box
### Steps to reproduce the problem
Create any new form. 
create select_one question with search('linked_self')
Open form and try to search
See attached sample form.
[Skills Provider v8.0.xlsx](https://github.com/smap-consulting/smapserver/files/2323478/Skills.Provider.v8.0.xlsx)

The workaround is to use the survey instance name
e.g search('linkeds107613390')

linked_self works in Fieldtask

(Optional) If this is reproducible on a Smap hosted server then include

### Server
sg.smap.com.au
### Organisation
? PREA ?
### Project
TS Test
### Form Name

Skills Provider v8.0
--
	Skills Provider v8.0

**Comment by atl2017** [comment]
I think it is related with issue #274

**Comment by atl2017** [comment]
I have tested with 
[TestLinkedSelf.xlsx](https://github.com/smap-consulting/smapserver/files/2408923/TestLinkedSelf.xlsx) and is OK. But may be who should close wiuld be @martingpritchard
