### ISSUE TITLE
BUG: Export of select_multiple missing column header and uses condensed format

### ISSUE THREAD

**Issue by martingpritchard** [smap-consulting/smapserver#361]
### Component fieldTask or SmapServer
Smap Server

### Version
18.07

### Expected Behaviour
SMAP exports data select_multiple form data in a format that can be imported into a new form built with the same form template. 

### Actual Behaviour
The export data.xml file does not contain a field name (column header) for fields defined as select_multiple. Data for the select_multiple field is exported, but in the compressed format where all responses to the question are displayed in one cell.
Data. including the select_multiple data, exported can not be imported into a new form created using the same form template. 

I'm not sure if this is a known limitation of SMAP or if desired functionality isn't working. I note that the export done using the Export menu from Analysis does export the select_multiple data in an expanded format (1 column per choice), but the column names don't look suitable for importing into SMAP as they have spaces.

### Steps to reproduce the problem
Create any new form. Include a select_multipe question
Complete the form and select two or more options for the select_multiple question.
Go to Analysis -> create table to display data for the new form.
Click blue Arrow to display import/export options. 
Export data from the form. 
Look at data file to see missing column header names and compressed export of select_multiple data.

(Optional) If this is reproducible on a Smap hosted server then include

**Comment by nap2000** [comment]
The bug where headers were not being written for select multiples has been fixed.  However it is normal that the select multiple data should be in compressed format for this type of export.  This export is only intended for data interchange not for analysis.

**Comment by atl2017** [comment]
Neil, I think you should close this issue.

**Comment by martingpritchard** [comment]
Thanks Neil and the SMAP team. I have test and problem resolved after Neil made change.  I'll see if I can close it

**Comment by martingpritchard** [comment]
As above. Tested. Bug fixed. Column header now showing for select_multiple
