### ISSUE TITLE
HIGH BUG - WEB FORMS - SEARCH Does not work if headers are uppercase PULLDATA also NOT.

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#363]
### Actual Behaviour:
![image](https://user-images.githubusercontent.com/29519901/44945437-30898100-adaf-11e8-875b-302dc83d56a4.png)
FT works fine but web forms does not. Situation is related with UPPERCASE headers:

![image](https://user-images.githubusercontent.com/29519901/44945477-0edcc980-adb0-11e8-82a0-cd85c554a1e1.png)

In order to let it work, I have to change headers to lowercase in csv file and also change value and labels

![image](https://user-images.githubusercontent.com/29519901/44945485-36339680-adb0-11e8-85c2-34ac1d40e466.png)

It is not necessary to change labels in pulldata: 

![image](https://user-images.githubusercontent.com/29519901/44945489-45b2df80-adb0-11e8-982e-0dc0fbca7391.png)

### Steps to reproduce the problem

Try to fill out in web forms:

**Comment by nap2000** [comment]
I'm not sure if the underlying problem has been fixed.  The error was caused by a blank line in the csv file.  The error message caused by this was misleading.  Blank lines no longer cause problems now however since the issue reports that the problem was solved by making the heading lower case there may be some other issue here.

**Comment by atl2017** [comment]
The error message was still displayed for the above form. I  fixed csv file and eliminate last two lines that were blank. Now is right.

Thanks.

**Comment by atl2017** [comment]
Organisation: SERACIS
Project:  Pruebas CONTROL DE INVENTARIO
Form: 1- SOLICITUD DE INVENTARIOS

When try to fill out with web forms pulldata does not get any data. Csv file has headers with uppercase letters. FT works fine

![image](https://user-images.githubusercontent.com/29519901/45450518-206e7d00-b69e-11e8-9dca-a567e79bf187.png)

Organisation: SERACIS
Project:  Pruebas ALEX
Form: 1- SOLICITUD DE INVENTARIOS TEST  

When try to fill out with web forms pulldata get all data. Csv file has headers with lowercase letters. 

![image](https://user-images.githubusercontent.com/29519901/45450640-7fcc8d00-b69e-11e8-9020-ef688aa208bc.png)

CONCLUSION: Problem still persists. In order to use webforms headers have to be lowercase.

**Comment by nap2000** [comment]
Ah yes.  Its ready to be released. I will update your server Saturday night.

**Comment by atl2017** [comment]
Hi Neil, Could you please confirm if server was updated? I did a test with 
Organisation: SERACIS
Project: Pruebas CONTROL DE INVENTARIO
Form: 1- SOLICITUD DE INVENTARIOS

and still does now work.

**Comment by nap2000** [comment]
Yep I tested it against the form you identified:
Organisation: ASORIOFRIO
Project: PRUEBAS DESARROLLO
Form Name: 1 - FT-CM-002 LISTADO DE PREDIOS HABILITADOS v3

Perhaps there is a second issue?

**Comment by atl2017** [comment]
Hi Neil,

When I reopened 5 days ago, I mentioned a different organisation/project/forms that works with  lowercase headers vs. uppercase letter. Personally I changed .csv file and form to refered to those new headers and works. So the situation for me is related with that.

Organisation: SERACIS
Project: Pruebas CONTROL DE INVENTARIO
Form: 1- SOLICITUD DE INVENTARIOS

**Comment by nap2000** [comment]
OK.  The original problem is fixed.  Can you describe the steps to reproduce this new problem.   For example is there a QR code that I need to enter?

**Comment by atl2017** [comment]
Organisation: SERACIS
Project: Pruebas CONTROL DE INVENTARIO
Form: 1- SOLICITUD DE INVENTARIOS

Steps:

1- Go to WebForms and select

![image](https://user-images.githubusercontent.com/29519901/46022586-8a2c5500-c0a8-11e8-9af3-9d806a72da20.png)

2- Introduce as QR this text: IMER/Imer/estadio/Rondero _/4738

![image](https://user-images.githubusercontent.com/29519901/46022670-aaf4aa80-c0a8-11e8-8637-6830d386563e.png)

3- When it is ok data is pulled and shown here:

![image](https://user-images.githubusercontent.com/29519901/46022801-ea22fb80-c0a8-11e8-9419-01926e16a866.png)

4- file csv is: PuestosSupervision.csv if you change for this: PuestosSupervisionTEST.csv that have lowercase headers. Both file are in shared resources.

**Comment by nap2000** [comment]
Seems to work when I tested it.  However I had to refresh the page to bring down the latest code change into the browser.  I have to admit it was surprising that this had to be done in this case.  However could you have another look at it after refreshing your browser?

**Comment by atl2017** [comment]
When you said seems to work was using [this form](https://app.kontrolid.com/webForm/s330_8064)?  I refreshed browser and the effects is exactly the same as I refered above

**Comment by atl2017** [comment]
Hi Neil, any news about it?

**Comment by atl2017** [comment]
Neil. I have checked again with the same results:

I cloned form above in

Organisation: SERACIS
Project: Pruebas CONTROL DE INVENTARIO
Form: 1- SOLICITUD DE INVENTARIOS Pruebas No usar

This form uses a cloned csv that has lowercase headers. It works fine:

![image](https://user-images.githubusercontent.com/29519901/47027186-96965180-d12c-11e8-8096-e700a32d1d38.png)

**Comment by atl2017** [comment]
Hi Neil,

My apologies. You were right. There were another situation that I finally found. I was referencing a column header as Puesto_Key instead of Puesto_key in pulldata. Now the behaviour is what I am expected:

![image](https://user-images.githubusercontent.com/29519901/47102464-7638c680-d202-11e8-8aa8-3e1b310426b6.png)
