### ISSUE TITLE
HIGH -WEBFORM does not display external data -  Issue or what is wrong with this form

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#366]
### Expected Behaviour: select_one "SELECCIONE LA INSTALACIÓN" should display list of places from external csv. FT does

![image](https://user-images.githubusercontent.com/29519901/46239018-3ba4e200-c358-11e8-9b38-583605cc7e35.png)

**Comment by nap2000** [comment]
Looking at this now

**Comment by atl2017** [comment]
tested Ok. Thanks a lot.
