### ISSUE TITLE
HIGH - WEB FORMS Page is not traslated as before

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#368]
### Actual Behaviour:
![image](https://user-images.githubusercontent.com/29519901/46737580-7add0800-cc61-11e8-8ef4-bf2feb4fca95.png)

You wrote me September 25th
QUESTION: Maybe since your latest update, webforms is not in spanish as before. Why?
ANSWER:  Hmm. Not sure. It will be fixed in the next release.  Its hard to predict the impact of updating to the next version of forked code.
--

**Comment by nap2000** [comment]
When I change my browser to use Spanish I see the following on the Kontrold server.  Webforms uses your browser setting rather than the application setting.
![spanish](https://user-images.githubusercontent.com/1946349/47132747-45838a80-d2f1-11e8-9df6-fca7f2faf8bf.jpg)

**Comment by atl2017** [comment]
My apologies.. It os Ok. I do not understand what happened.  Thanks
