### ISSUE TITLE
BUG - LINKED SELF - Does not recognize multiple choices label

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#370]
### Expected Behaviour: Multiple choices labels is a standard feature use in search. It works when linked form are used as linked_sxxxxx:

![image](https://user-images.githubusercontent.com/29519901/46741510-cba52e80-cc6a-11e8-956a-e578b950ad82.png)

### Actual Behaviour: linked_self DOES NOT work with multiple choice labels and nothing is displayed:
![image](https://user-images.githubusercontent.com/29519901/46741595-fd1dfa00-cc6a-11e8-8fd4-64140e1bdd84.png)
Only 1 label is accepted

### Forms Name: TestLinkedForm  & TestLinkedSelf

Just start form and see differences. Both have multiple choice labels.

**Comment by nap2000** [comment]
Select multiple with linked_self works.  The problem was because you had multiple comma separated questions that made up the label.   So a different issue.

**Comment by nap2000** [comment]
I have now fixed the issue with using multiple questions in the label separated by commas.  Actually my apologies having re-read the issue I see you were specifically calling out the issue of having multiple choice labels.

**Comment by atl2017** [comment]
Tested Ok.
