### ISSUE TITLE
FUTURE - H5 - ENHANCEMENT - TASK GROUP new assign type: Neighbor

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#376]
### Expected Behaviour: The idea is to take advantage of available Coordinates data from users (either GPS capture or GPS trail better) to do nearest neighbor search and assign tasks based on that.

So tasks with target lat,lon are assign to nearest neighbor user. It should apply only for new submissions and assign it on the fly (one by one).  

It would be an excellent tool for services call that need to be attended by a closest person. Note: If an assigned task is rejected by an user it has to be reassigned to the next nearest neighbor.

![image](https://user-images.githubusercontent.com/29519901/47498680-96304180-d823-11e8-85bd-49712014eff4.png)

 ### Ideas how to implement: An straightforward way could be use postgresql Example: (https://artlembo.com/2016/04/26/k-nearest-neighbor-with-postgres/) Also I found a more sophisticated [patented solution](https://roadsindb.com/).  

Another way could be to implement a service from google maps [like](https://developers.google.com/maps/documentation/javascript/distancematrix).

It could be launch as Beta while we measure how effective and practical is.

**Comment by nap2000** [comment]
Nice.   We could also do this as geofencing by specifying a radius from a point and whenever anyone enters that region they get assigned the task.

**Comment by atl2017** [comment]
Yes...you got it! excellent feature for field service solution

**Comment by atl2017** [comment]
> Nice. We could also do this as geofencing by specifying a radius from a point and whenever anyone enters that region they get assigned the task.

Today was highlighted as feature that competitors have. It works lightly different because they use a list of preload locations and let user do only tasks/forms that are in a geofence.

**Comment by atl2017** [comment]
Future wish list. We would like to use more geofence new feature.
