### ISSUE TITLE
BUG - Mistyping button names in Editor

### ISSUE THREAD

**Issue by ztatu** [smap-consulting/smapserver#38]
### Actual Behaviour: 

![image](https://user-images.githubusercontent.com/29519901/28461656-3eb76a84-6ddd-11e7-8a15-375c880409fd.png)

Note following mistyoing texts:  Vidoe (Video)  GPS Line twice (GPS Area)

**Comment by ztatu** [comment]
Did you fix "Vidoe" in english instead of "Video"?

**Comment by nap2000** [comment]
Ah I have now

**Comment by ztatu** [comment]
Tested OK
