### ISSUE TITLE
HIGH - ENHANCEMENT - Activity User - Include _start _end and other columns and filter

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#399]
### Expected Behaviour: The need from a customer is to have a view of all activity of an user with the same characteristics tables have including edit in webform / download pdf and filter by. Of course It would have only common columns as metadata.

![image](https://user-images.githubusercontent.com/29519901/49824741-c50d6300-fd50-11e8-948d-bf3cf794fa59.png)

Idea behind this is to provide a way to check with details activity of an specific user.  It is based on one report competitor has:

![image](https://user-images.githubusercontent.com/29519901/49825073-8926cd80-fd51-11e8-97d2-f21cb04dd1c9.png)

Later we can also consider a report by user to download ALL PDF reports between dates (metadata):

![image](https://user-images.githubusercontent.com/29519901/49825270-02262500-fd52-11e8-9ea2-32dd14a3b4ae.png)

**Comment by atl2017** [comment]
I do Not think so. Because it is needed to access Edit web and select pdf to download. User activity as Excel only displays récords without any interaction. Or to start a zip report with Calendar as filter with Excel récords as you mentipn but also related pdf reports.

**Comment by nap2000** [comment]
Ok so a table for a specific user but many all forms in the current project
only?

**Comment by atl2017** [comment]
In all projects. 

It should answer the question: What did a user do today or yesterday or specific priod of time (it could include day-hour to select)

**Comment by atl2017** [comment]
Regarding to 1- Above for example user: claro1 organisation: GRUPO COLBA with security group: _view data_ have access to my user activity in all organisations and download pdf reports:

![image](https://user-images.githubusercontent.com/29519901/50542790-7145ab00-0b93-11e9-876f-fe029130b284.png).

I think user should not view all security groups

**Comment by atl2017** [comment]
Hi Neil,

Regarding own submissions ..great. Maybe it is related and you can consider it for  #176  

It is Ok additional columns for new data.

Thanks a lot.

**Comment by atl2017** [comment]
Hi Neil, it would be nice to include the additional columns (*_start*, *_end*, *_hrk
(Key)* and *instance name*) soon in order to have availability of all new data for 2019 records.

Regarding numbered wish list 1- and 6- were done.
 2- and 3- still pending as mention above. I would close this issue after that.
 4- That is related as .zip report I will raise as new issue. 
 5- Time series and static ..whenever you want.

**Comment by atl2017** [comment]
Almost ready..

Please consider header names traslated as in Analysis - Subject: Survey

Please include scheduled_start

![image](https://user-images.githubusercontent.com/29519901/50905443-d9488c80-13f0-11e9-9d9f-c4615597de31.png)

**Comment by atl2017** [comment]
Tested Ok:

![image](https://user-images.githubusercontent.com/29519901/50967311-c643c400-14a5-11e9-9694-bce7e5e06fc3.png)

Still pending to close the issue:

1- Traslation for Instance Name / Start Time / End Time
2- Extend Date Filter to include by Start and/or End times

**Comment by atl2017** [comment]
Still pending to close the issue:

1- Traslation for Instance Name / Start Time / End Time  **(Not big deal, it is easy to understand)**
2- Extend Date Filter to include by Start and/or End times **(Highly recommeded)**
3- Include scheduled_start_time **(recommended)**

**Comment by atl2017** [comment]
Still pending to close the issue:

2- Extend Date Filter to include by Start and/or End times **(Highly recommeded)**
3- Include scheduled_start_time **(recommended)**

**Comment by atl2017** [comment]
Tested OK.
