### ISSUE TITLE
BUG - Too slow to edit form

### ISSUE THREAD

**Issue by ztatu** [smap-consulting/smapserver#40]
### Steps to reproduce the problem

https://drive.google.com/open?id=0B966-DLxVMApWnJYUi1Ub1ZqZ1U

(Optional) If this is reproducible on a Smap hosted server then include

**Comment by nap2000** [comment]
Is this still slow?

**Comment by nap2000** [comment]
How about now? A record was being written to the survey change log every time an external CSV file that was used by that survey was changed.  This was creating very large change logs that were being loaded with the survey for editing.  Changes to external files are no longer recorded in the survey change log and loading should be faster.

**Comment by ztatu** [comment]
12 seg to open example to reproduce described above (Form Name: Pulldata).

I think situation is other. 

 1-  I did a simple note question "Hello World" and it takes the same amount of time to open.

Server: Kontrolid
Organisation: Zarkman
Project: testAlex
Form Name: HelloWorld

 2- I create a new form, and the time between click **create button** and being ready to edit form was aproximately 12 seg.

![image](https://user-images.githubusercontent.com/29519901/28756832-c5aded64-753b-11e7-9f1e-ab0171fccd98.png)

**Comment by nap2000** [comment]
OK.  I have done some more performance tuning.  Any improvement?

**Comment by ztatu** [comment]
YES!  less than 2 s to load PullDataOnly.  1 s to load HelloWorld.  Congrats!
