### ISSUE TITLE
ADMIN - ENHANCEMENT - Include a limit of number of submissions per organisation

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#408]
### Expected Behaviour: Extends current constraint to Allow Submissions with a limit.

![image](https://user-images.githubusercontent.com/29519901/50742621-e6406280-11db-11e9-8bfc-5f23ccb7b6ea.png)

X Allow submissions. Limit (number or empty for unlimited) Period monthly or empty for no due date  ().  

With this suggested feature I am thinking about the chance to offer packages of number of submissions in addition to users / total submissions. 

You have commented: "Yep sounds good.  I am adding the ability to restrict.  It should be possible to automatically apply that restriction if payment is not received or after some other event such as an initial free offer."

**Comment by atl2017** [comment]
Hide to be consider in future

**Comment by atl2017** [comment]
I would like to reconsider to offer prepaid submissions packages.

**Comment by nap2000** [comment]
Will be included in the april release.

**Comment by atl2017** [comment]
Great. Perhaps and taking advantage of our strong notification system, we could include a prealert emails to notify when organisation have achieved 90% total usage, 95% and 100%.

**Comment by atl2017** [comment]
Tested OK. Thank you very much.
