### ISSUE TITLE
Missed images in specific records

### ISSUE THREAD

**Issue by ztatu** [smap-consulting/smapserver#41]
### Form Name: ReporteDiario

pri_key: 324, 351, 352.    Check analysis and there are one missed image each record. What could have happened? 

If situation is uploading issue, Is there a way for user to know that situation a try to repeat?

**Comment by nap2000** [comment]
Which records have a missing image and for which question.  I had a quick look and couldn't see anything obviously missing.

**Comment by ztatu** [comment]
Records:  324, 351, 352.

**Comment by nap2000** [comment]
Ah ok. Yep sorry.

**Comment by nap2000** [comment]
The photograph is not required in the survey.  There is also no sign of a broken link in the results.  If there was a problem uploading an image then I would still expect the link to the image to have been record.  Why are you certain that a photo was taken with these records?

**Comment by ztatu** [comment]
Below image is a screenshoot of record 324 with Browse results. See text picture instead of image (https://app.kontrolid.com/1500911020658.jpg)

![image](https://user-images.githubusercontent.com/29519901/28746372-daac5052-7450-11e7-928c-4d97b6609ae7.png)

**Comment by nap2000** [comment]
Do you have access to the phone that submitted record 324.  If so is there an image 1500911020658.jpg on that phone?

**Comment by ztatu** [comment]
Yes I Have. 

I guess it could be an uploading process that was temporaly interrupted. If I found photos I supossed I just edit web forma and add it. Am I right?

**Comment by nap2000** [comment]
If the uploading process was interrupted then there should be an error.  And the user should then have to re-upload.  

I couldn't find any errors on the server.  Possibly the image was deleted before uploading.  Maybe there was not enough space on the sdcard, or it could be there is a bug either on the phone software or the server.  However apart from the image being missing I can't find any errors.

Yes if you can find the image then you can add it through web forms.

**Comment by ztatu** [comment]
Yes. I confirmed it was phone issue because we could not find image.

Thanks
