### ISSUE TITLE
HIGH - ENHANCEMENT - Set "moving backwards" from FieldTask Options

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#413]
### Expected Behaviour: Ability to set Set "moving backwards" from FieldTask Options
![image](https://user-images.githubusercontent.com/29519901/50938289-89e07b80-1445-11e9-9c5b-ece28452df44.png)
![image](https://user-images.githubusercontent.com/29519901/50938125-d5465a00-1444-11e9-82e5-06a73b80ce5d.png)
![image](https://user-images.githubusercontent.com/29519901/50938318-aaa8d100-1445-11e9-8510-9d8bcb9bc6cf.png)

**Comment by nap2000** [comment]
This update is ready to deploy and will be included in the next fieldTask release

**Comment by atl2017** [comment]
Tested OK
