### ISSUE TITLE
HIGH - BUG - ANALYSIS audit=yes is not working in API

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#414]
### Actual Behaviour:  audit=yes is not working in API
![image](https://user-images.githubusercontent.com/29519901/50945611-7ba15800-1463-11e9-9216-750491d7d7b7.png)
![image](https://user-images.githubusercontent.com/29519901/50945668-bc00d600-1463-11e9-9138-025056b795fb.png)

**Comment by nap2000** [comment]
There is a new version of the fieldTask App that fixes this problem.  Its in the app store and I have made available a new version of the kontrolid app for you.

**Comment by atl2017** [comment]
Tested OK

![image](https://user-images.githubusercontent.com/29519901/51224072-5ce30b80-1912-11e9-86b6-b1680023263b.png)
