### ISSUE TITLE
URGENT - BUG - Browse Result freeze and do not display any data

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#417]
### Actual Behaviour:  Date question is not gotten:
![image](https://user-images.githubusercontent.com/29519901/51323447-39b17c80-1a36-11e9-8852-da5b4f7c16df.png)
![image](https://user-images.githubusercontent.com/29519901/51323571-96ad3280-1a36-11e9-8594-ce9661441198.png)
### Steps to reproduce the problem:
Just goes to Browse Data in any form

**Comment by nap2000** [comment]
Its fixed.  However the primary key is not showing in browse results.  I need to fix up the use of the "ID" display name.  Will do this in the overnight release.

**Comment by atl2017** [comment]
Tested OK
