### ISSUE TITLE
HIGH - BUG - Records marked as bad are listed in linked forms

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#428]
### Actual Behaviour:
FT displays record marked as bad no matter record has been marked as bad:
![image](https://user-images.githubusercontent.com/29519901/53085921-fb462c00-34d1-11e9-9096-792bfc48d78b.png)

Generated csv in device contains bad record:
![image](https://user-images.githubusercontent.com/29519901/53085933-00a37680-34d2-11e9-91ac-23da495ced52.png)

Source where is shown that record was marked as bad:
![image](https://user-images.githubusercontent.com/29519901/53085948-0731ee00-34d2-11e9-85e2-2a9ced7334b4.png)

**Comment by nap2000** [comment]
Records marked bad are not included in the csv data downloaded to other forms.   The problem is that the CSV file is not regenerated if a record is marked bad.  So if you were to mark the record bad and then another record was submitted to that form the csv file would no longer include the "bad" record since submitting the new record would have initiated ites regeneration.   I will look at adding a solution to this problem.

**Comment by atl2017** [comment]
Understood, I have added another record: 11 (Joan) and Neil, marked as bad was not shown anymore:

![image](https://user-images.githubusercontent.com/29519901/53140920-3f7e0e80-355c-11e9-88f2-638ecffc7b7e.png)

Thanks

**Comment by nap2000** [comment]
Ok.  Probably wasn't necessary to close the issue.  It is something that needs to be addressed.  However it is also tied up in a bigger todo item related to improving efficiency of these csv downloads.  I've already added the lookup_choices() function so you can get a choice list directly from the server when there are a very large number of reference records.  However in the case where you have a middling number, say 100,000 and you want to work offline then every time a new record is added then all these 100,000 records are regenerated and re-downloaded for every user that references them.   I'd like to just send down the delta, that is the change.  So ideally if you mark a record bad then just that information should be sent and update the csv file on the phone.
