### ISSUE TITLE
Enhancement - Analysis - Advanced Filter - Cater apostrophe in text

### ISSUE THREAD

**Issue by martingpritchard** [smap-consulting/smapserver#434]
### Version
19.02
### Expected Behaviour
User should be able to search for text that contains an apostrophe (') using the Advanced Filter section of the Analysis feature

### Actual Behaviour
The apostrophe is  currently not escaped and cannot be searched for. Currently SMAP shows error
"Missing matching single quote: ${first_name} like '%'Akeola%'"
when try to search for ${first_name} like '%'Akeola%'
### Steps to reproduce the problem
Go to Analysis. 
Open table Application Form
Click gear icon
Enter ${first_name} like '%'Akeola%' into advanced filter box.
Click Save
(Optional) If this is reproducible on a Smap hosted server then include

### Server
sg.smap.com.au
### Organisation
PREA
### Project
Tonga Skills
### Form Name
Application form.

**Comment by nap2000** [comment]
Will be included in elease 20.04
