### ISSUE TITLE
ENHANCEMENT - New security group - Tasks

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#441]
### Expected Behaviour: A customer request a new secutiry group that only view Tasks
![image](https://user-images.githubusercontent.com/29519901/54399682-96739100-468d-11e9-9f50-30ac962553b7.png)
To view this:
![image](https://user-images.githubusercontent.com/29519901/54399588-164d2b80-468d-11e9-8001-fa57c7154843.png)

**Comment by atl2017** [comment]
Due to your recent big improvements you have done to tasks module it is more relevant to split "Analyst" from "Task creation".

**Comment by atl2017** [comment]
Another alternative for the name "Scheduler" or "Task Manager"

**Comment by nap2000** [comment]
With the new "console" function, accessible if you have "manage" role you will be able to create tasks to update specific cases.   I think it would make sense to give this person who has the manage role also access to the tasks module.

**Comment by nap2000** [comment]
In 19.08 users with Manage" will be able to edit tasks as well as use the console.  Tasks are the console are interconnected.  Does this address the issue

**Comment by atl2017** [comment]
I have tested and "manage" needs "analyst" to send a notification. So it is not possible to have "view data" + "manage" being useful.

**Comment by atl2017** [comment]
Grupo COLBA have requested the same. They have assigned some people to schedule tasks but they do not want them to have access to beither forms nor shared resources.  So apparently it is very important to split tasks management from analyst.

**Comment by atl2017** [comment]
Tested OK.
