### ISSUE TITLE
HIGH - FT - BUG - TASKS EDITION does not update changes in FT

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#462]
### Actual Behaviour: I found out that Task editon is not updated in FT. I tested with Name / Guidance and location
![image](https://user-images.githubusercontent.com/29519901/56498934-b0dd2d80-64c9-11e9-9a00-105c559cbc33.png)

The only way to see updated changes is first "Delete Saved Form" and then refresh:

![image](https://user-images.githubusercontent.com/29519901/56499185-e9c9d200-64ca-11e9-84f8-e5e425eb6c0b.png)

**Comment by atl2017** [comment]
Tested in FT 6.20.0  issue still remains

**Comment by nap2000** [comment]
You can now update the:
   title
   guidance,
  GPS coordinates
  NFC

Does anything else need to be updated?   I don't think we should allow the survey to be changed as that will affect downloaded instance data.

**Comment by nap2000** [comment]
Included in 6.20.1

**Comment by atl2017** [comment]
Tested OK. I completely agreed.
