### ISSUE TITLE
H1 - BUG - Download XLS is downloading the first (version1) not latest

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#465]
### Form Name: TestReplacement

Try Forms -> Download -> Original File (Version 1) and compare with Forms -> Download -> XLS Form (Version 5) . Both are similar.

Also check for Changes log:  Tools - > Changes: See that there were few changes:

![image](https://user-images.githubusercontent.com/29519901/56581042-ab4f1880-6599-11e9-979a-310d858bfaf8.png)

**Comment by atl2017** [comment]
Hi

Still pending. It happened gain, we made a mistake replacing a form a we could not recovery original xlsform. It was necessary to look for our backup in desktop.

**Comment by atl2017** [comment]
Hi Neil,

See image below. I exported xls and only have one question. Editor has 2 question. I strongly recommend check this soon.

Thks

![image](https://user-images.githubusercontent.com/29519901/58065405-3b599100-7b4b-11e9-9f8e-7a906c42330d.png)

**Comment by atl2017** [comment]
Could you please help me with this issue.

**Comment by nap2000** [comment]
All the versions of xlsForm uploaded including the original and any replacements are recorded in the change history.   

I think the best solution might be to remove the option "Original File" from the download dialog.  This confuses people. So from that dialog you would just download the latest definition generated by the server.

To get an original uploaded XLS file the user can go to the "VIew changs" page in the online editor.

**Comment by atl2017** [comment]
Agreed.

**Comment by atl2017** [comment]
Pending to consider my suggestion to close issue.

**Comment by atl2017** [comment]
Close Issue and consider next stpes as future
