### ISSUE TITLE
FT - ENHANCEMENT - An alert when media should be uploaded and is not found.

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#469]

**Comment by atl2017** [comment]
Future wish list

**Comment by nap2000** [comment]
I think the main reason for this is when a form is saved as draft before being sent. Either deliberately or because there is no network connection.  In those cases media was not being saved.  This has now been fixed so the problem should diminish substantially.

**Comment by atl2017** [comment]
Case reported by email

**Comment by atl2017** [comment]
No new issues have been reported. So for now rhis issue will be close.
