### ISSUE TITLE
BUG - TASK GROUP - Pre-populate form with existing data display error when target form contains subform

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#470]
### Actual Behaviour: Pre-populate form with existing data DOES NOT work if target form include a repetition group (subform).

![image](https://user-images.githubusercontent.com/29519901/56764856-5ebb3700-676b-11e9-91b3-cde1e7251cdf.png)

### Forms Names Target: TestGPSTask_Clone (Works) 

![image](https://user-images.githubusercontent.com/29519901/56765638-1735aa80-676d-11e9-94a7-03d701ed9759.png)

### Forms Names Target:  TestGPSTask_Clone_Subform (Does not wotk)
![image](https://user-images.githubusercontent.com/29519901/56765675-316f8880-676d-11e9-8169-203906cd33bb.png)

The only difference between Form target is a subform

![image](https://user-images.githubusercontent.com/29519901/56765841-9f1bb480-676d-11e9-8829-7905279d1add.png)

**Comment by nap2000** [comment]
This may be fixed.  I fixed a similar issue in last nights release where only the first record of a repeating subform was populated.  It looked like it was all working when I tested it.

**Comment by atl2017** [comment]
No. It has not been fixed already. You can check trying to edit form as highlighted.

![image](https://user-images.githubusercontent.com/29519901/56876403-bd531000-6a0c-11e9-8a0f-366b13518093.png)

**Comment by atl2017** [comment]
Tested with FT 6.20.0 and fail!

**Comment by atl2017** [comment]
Trick: Include the same repeat in existing form no matter it is empty
