### ISSUE TITLE
FUTURE - ENHANCEMENT - Include PDF link as attached option in notifications

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#477]
### Expected Behaviour: Taking advantage of new feature of PDF url link in API, I would like to propose an option of PDF link as an alternative of PDF document. That could reduce data traffic in emails for customers that need it.

Option could look like this: 

![image](https://user-images.githubusercontent.com/29519901/58267238-d79cb700-7d48-11e9-999d-3674f9049212.png)

**Comment by nap2000** [comment]
Anyone receiving the email with a link would need an account and to logon to the server.   Is this ok?

**Comment by atl2017** [comment]
Hmm. Well, it would be a constraint similar to "web form" (enum). I supposed user should have "Analyst security group" instead. Am I right?

**Comment by atl2017** [comment]
Another alternative could be save PDF url as metadataquestion thatn can be included in Content (Body text).

Example: "Link to pdf here: ${pdfurl}

**Comment by atl2017** [comment]
Future wish list

**Comment by atl2017** [comment]
If we currently have pdf as url in API data. It should be straightforward to implement, right? So it could be included also as part of sms
