### ISSUE TITLE
HIGH - BUG - Dynamic url markdown is not working in web forms

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#478]
### Actual Behaviour

Example:
![image](https://user-images.githubusercontent.com/29519901/58523250-5d759380-8189-11e9-97ee-74e175fc2029.png)

Is displayed as:

![image](https://user-images.githubusercontent.com/29519901/58523264-6b2b1900-8189-11e9-9f30-93bc685711d0.png)

**Comment by nap2000** [comment]
Enketo preview gives the same result so it looks like an issue with the underlying enketo code.

**Comment by nap2000** [comment]
You can use html instead.   So it may not be necessary to fix this one.
![url](https://user-images.githubusercontent.com/1946349/58616224-781e4880-8300-11e9-8277-9c9935e18b7d.jpg)

**Comment by atl2017** [comment]
Tested Ok. Thanks
