### ISSUE TITLE
HIGH - BUG - DateTime widget does not display data in shared table as read only

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#491]
### Actual Behaviour: There are issues with dateTime and time widgets when are used in shared data tables with read only as in Task Flow.

For example, below is the image that displays data is not gotten in dateTime widget if it is in a form in a group and read only.

![image](https://user-images.githubusercontent.com/29519901/59706815-e69b4b80-91c6-11e9-9b43-afbd80f170ab.png)

Also data gotten by Web Forms are displayed as error when time is used
![image](https://user-images.githubusercontent.com/29519901/59706845-f7e45800-91c6-11e9-8efe-408f844bab45.png)

**Comment by nap2000** [comment]
I've made some updates.  FieldTask should now display date time correctly.  I have also added time zone to time question for new forms.  The latter should help if the timezone changes between creating of the time and then viewing it again.

**Comment by atl2017** [comment]
So it means you should send me a beta APK to test it.

**Comment by atl2017** [comment]
Tested Ok in FT.

I will raise a new issue for time in web form.
