### ISSUE TITLE
Installation 16.04.4

### ISSUE THREAD

**Issue by acopernic** [smap-consulting/smapserver#5]
Hello,
Small problem when I install server on Ubuntu server (16 or 14). Can't find deploy.sh

**Comment by acopernic** [comment]
By changing the path in the install.sh for deploy.sh it is working.

**Comment by nap2000** [comment]
Hi, Thanks for your feedback and for trying out the system.   The install script should assume the deploy script is in ../deploy.   If you have any more thoughts on this issue let me know, could it be related to configuration of your ubuntu machine or is there a specific error in the install script.
