### ISSUE TITLE
H0 - ENHANCEMENT - Task API - Create a relation with submitted forms

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#500]
### Expected Behaviour:

As was sent by email june 6ht 2019:

One of our customer needs a relation between Completed Tasks and Data related.  A suggestion could be to include Key (record) as part of Tasks API and also if it is possible to include in in table, perhaps as hyperlink to data.

What I think is:  To include prikey in TASK API at least, optional and in addition to, include links to webforms and link to pdf in Tasks API. 

![2](https://user-images.githubusercontent.com/29519901/62810609-14fd1f00-bac4-11e9-81fd-1470948b9316.png)

I mean this API
![3](https://user-images.githubusercontent.com/29519901/62810631-2f36fd00-bac4-11e9-999a-74aa19813804.png)

With this:
![4](https://user-images.githubusercontent.com/29519901/62810646-3b22bf00-bac4-11e9-93ef-0f09528dbe30.png)

**Comment by nap2000** [comment]
This was partially implemented in the console release.   On the task management page if you select the edit button for a task you will see at the bottom of the dialog a button "Show in Console".  Select that and you will see the data in the console.   From their you can edit the data and manage the task.

I am working on adding a link to the API

**Comment by atl2017** [comment]
Nice to have API soon.

**Comment by atl2017** [comment]
![image](https://user-images.githubusercontent.com/29519901/65569859-9c8fd780-df24-11e9-8ef6-6940d3a6b937.png)

Tested OK. Thank you very much

**Comment by atl2017** [comment]
Currently is not working when status is "submitted"

Orgnanisation: Kontrolid
Project: TestTasks
TaskGroup: Alex´s test

![image](https://user-images.githubusercontent.com/29519901/69501797-63e58d80-0ed6-11ea-8e27-7832724bd997.png)
![image](https://user-images.githubusercontent.com/29519901/69501807-78298a80-0ed6-11ea-9b91-f90ce52217d6.png)

When click to json_data
![image](https://user-images.githubusercontent.com/29519901/69501836-c474ca80-0ed6-11ea-844a-ff04221ff348.png)
![image](https://user-images.githubusercontent.com/29519901/69501844-db1b2180-0ed6-11ea-939a-11d1cfd61ac1.png)

**Comment by atl2017** [comment]
Tested Ok. Thanks
