### ISSUE TITLE
ENHANCEMENT - Tasks Module - Include a new state: "Delayed"

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#502]
### Expected Behaviour:

As was sent by email July 23th 2019:

I was thinking about it and find out that there are advantages to consider "Delayed" as status not only to be displayed differently. What about filtering in Task Modules or with API?  

Status is a state  so a task could be   Assigned -> Completed  or  Assigned -> Delayed -> Completed

As was sent by email July 22th 2019:

What about include a new Tasks status in life cycle:  "Delayed" . It happens when a scheduled task has not been accomplished at start time. Delayed tasks should be identified as RED color in backgroud. Perhaps "Rejected" tasks should have other color like black or brown. Depends of your comment I will raise as an issue.

**Comment by nap2000** [comment]
This will be included in version 19.08

**Comment by atl2017** [comment]
Tested Ok. I wonder if it should consider start time instead of end time.
