### ISSUE TITLE
BUG - TASKS - Export XLS is not considering timezone

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#507]
### Actual Behaviour: As exported by : Task managemente - File - Export XLS:

![image](https://user-images.githubusercontent.com/29519901/63608994-d1aeb000-c59b-11e9-8d8d-3e87a591db55.png)
Wrong:
![image](https://user-images.githubusercontent.com/29519901/63609066-fc990400-c59b-11e9-9bc4-f1339d5f6182.png)

Right:
![image](https://user-images.githubusercontent.com/29519901/63609124-205c4a00-c59c-11e9-8e48-0c5c84ff3624.png)

**Comment by nap2000** [comment]
The timezone difference was being applied twice.  Once when retrieving the data from the database and once when writing to the spreadsheet.

**Comment by nap2000** [comment]
Timezone was also not being used when applying the period filter.  Ie retrieving tasks within the last 7 days or month.

**Comment by atl2017** [comment]
Tested Ok.Thanks
