### ISSUE TITLE
BUG - In Email Tasks Web form settings are not used

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#510]
### Expected Behaviour: If we set web form options it is expected to be used in email tasks

![image](https://user-images.githubusercontent.com/29519901/63803339-4c4c3800-c8da-11e9-87f0-fc0a7c88f74d.png)

### Steps to reproduce the problem

(Optional) If this is reproducible on a Smap hosted server then include

**Comment by nap2000** [comment]
Seems to be fixed
