### ISSUE TITLE
ENHANCEMENT - Data API - Option to be displayed in Reverse order

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#513]
### Actual Behaviour: When we use the data api like: https://app.kontrolid.com/api/v1/data/s98_6866, data are displayed from first record, so if we use limit like https://app.kontrolid.com/api/v1/data/s98_6866?limit=1, only first record is displayed.

**Comment by atl2017** [comment]
Could you please take a look of this. Perhaps it would be easy to implement. Thanks

**Comment by nap2000** [comment]
You can use the sort parameter in the API and specify prikey with direction "desc".  So for example:

https://ubuntu1804.smap.com.au/api/v1/data/s12_67?links=true&sort=prikey&dirn=desc

**Comment by atl2017** [comment]
Understood!. Thanks.

![image](https://user-images.githubusercontent.com/29519901/79031308-8f0a0a00-7b63-11ea-8704-6096366e9bb4.png)
