### ISSUE TITLE
ENHANCEMENT - Late status - Icon in FT and Map Web

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#515]
### Actual Behaviour:
Late task are colored as White n Task Map
![1](https://user-images.githubusercontent.com/29519901/64343538-50e7af00-cfb2-11e9-89c3-fd5d983a7a24.png)
Late task are not colored in FT
![1 (1)](https://user-images.githubusercontent.com/29519901/64343515-47f6dd80-cfb2-11e9-8a00-dcc1c3d05715.png)

**Comment by nap2000** [comment]
I've updated fieldTask to show late tasks as red and rejected tasks as brown.  Have a look at that and if it is heading in the right direction I will make the browser interface consistent.

**Comment by atl2017** [comment]
Regarding you wrote last email I agreed about differences between lala in mobile vs server "
I think of duration as how long they have to do the task.  Ie it may take an hour.  The mobile phone user is late if they have not started the task by th escheduled start time.   However it is not late at the server until after the scheduled finish time when they should have submitted it." 

Pending to close the issue:  Web Forms = FT. Example below, tasks should be in red due to current time > scheduled start time:

![image](https://user-images.githubusercontent.com/29519901/65816610-750a6a80-e1c3-11e9-8a87-98f124c160b5.png)

**Comment by atl2017** [comment]
Hi Neil,

In order to continue your excellent work about this, we need to fix some issues in FT:

1- Apparently NFC tasks are not included as "late"
2- In MAPS, "late" tasks are displayed in yellow "assigned" tasks
![image](https://user-images.githubusercontent.com/29519901/65914762-9b80ff00-e397-11e9-8354-e897e9a27a73.png)

![image](https://user-images.githubusercontent.com/29519901/65914713-84421180-e397-11e9-80d2-27557bbbd1ea.png)

![image](https://user-images.githubusercontent.com/29519901/65914805-b3f11980-e397-11e9-93a1-8820eb2d5812.png)

**Comment by atl2017** [comment]
Neil, pendind late icon red implementation in Maps.

**Comment by atl2017** [comment]
Is it viable to update icons in Maps to include late?

**Comment by nap2000** [comment]
Yep its viable and is now in release 6.100 of fieldTask

**Comment by atl2017** [comment]
Tested Ok. Thanks
