### ISSUE TITLE
HIGH - ENHANCEMENT - Notifications - Opt in (confirm subscription) prior to send first email

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#516]
### Expected Behaviour:  After a Notification is created, email´s recipients should be check against subscribers list. Addresses that are not included would be receive an opt in email confirmation. It could be like we use after a subscription.

![image](https://user-images.githubusercontent.com/29519901/64343950-14688300-cfb3-11e9-9f8a-d727351207d3.png)

**Comment by atl2017** [comment]
Examples below of October 2019.  It has been some bounced emails due to mistyping or system do not accept email from us, etc: 

![image](https://user-images.githubusercontent.com/29519901/66254356-cc1bbc80-e73a-11e9-908d-04b6d142b6ea.png)

**Comment by atl2017** [comment]
The more customers we have the more bounces we hahave had due to this issue. This will fix for example when a email was misspell.

**Comment by atl2017** [comment]
Recent bounces for this issue:

![image](https://user-images.githubusercontent.com/29519901/69723166-f197c780-10e6-11ea-8ce9-4b22ab03773c.png)

**Comment by atl2017** [comment]
Another example:

![image](https://user-images.githubusercontent.com/29519901/69997930-42625280-1523-11ea-8276-35c5b8d78b14.png)

**Comment by nap2000** [comment]
Let me see if I understand.   For each email in a notification, If there is no record of the email in the subscription table, ie they are neither subscribed nor unsubscribed then an entry will be added that they are unsubscribed and an opt in email will be sent.  Until they respond to that opt in email no emails will be sent to the user.

Does this also apply to dynamic emails extracted from data?

**Comment by atl2017** [comment]
Yes. Exactly. What Will happen with emails? Remains unsent or hold and are
sent after confirm suscrption?

**Comment by atl2017** [comment]
It could behave as current when an user have opt-out, except message should be different. Something like "pending for opt-in":

![image](https://user-images.githubusercontent.com/29519901/71949802-e7b3ba80-31a2-11ea-9ec1-5e33e9971866.png)

It would include dynamic emails also.

**Comment by atl2017** [comment]
Hi Neil,

As you can see issues are getting higher, thats why it is a current priority:  0.23% Bounced emails.
![image](https://user-images.githubusercontent.com/29519901/72722385-315db700-3b4c-11ea-8366-dda3dac8b7f8.png)
Thanks in advance.

**Comment by nap2000** [comment]
ok.  So is this what you want:

**Firstly response to an email being sent:**

1) The email address has opted in.  The email is sent.
2) The email address has opted out.  The email is discarded.
3) The email address has been sent an opt in message.  The email is put on hold.
4) None of the above then an opt in message is sent to the email address and the email that triggered this is put on hold.

**Secondly a positive response is received to an opt in email**

1) The email address is set to opted in.
2) Any on hold emails that were created while waiting for the opt in are sent.

**Thirdly a negative response is received to an opt in email**

1) The email address is set to opted out
2) any on hold emails are discarded

Does this also apply for new user account emails?  I'm thinking not.  Only notification emails.

**Comment by atl2017** [comment]
Yes. You got it!

Only notification email.

**Comment by atl2017** [comment]
Thank you very much! 

Tested OK

**Comment by atl2017** [comment]
Just to confirm how effective has been this solution: Delivery rate have been > 99.5%

![image](https://user-images.githubusercontent.com/29519901/77207918-98560880-6ac8-11ea-8803-1b85179f9723.png)

Thanks
