### ISSUE TITLE
H1 - HIGH BUG - Key question es not working in parent form

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#525]
### Actual Behaviour:

![image](https://user-images.githubusercontent.com/29519901/65771087-0c58ba80-e0fd-11e9-918a-ee5ae57fb888.png)

### Steps to reproduce the problem

Fill out form "reporte de incidentes"

**Comment by nap2000** [comment]
There is not enough information here on what the problem is.  I completed the form "report de incidentes" twice but it wasn't clear to me that there was an error.   I've marked the two records as bad so they don't affect your analysis.

**Comment by atl2017** [comment]
Sorry for not being clear:

## Steps to reproduce the problem
1- Fill out form "reporte de incidentes"  as follow:
a-  First question write anything
b- Select red option to launch form:
![image](https://user-images.githubusercontent.com/29519901/65817016-0380eb00-e1c8-11e9-83ac-97f5b6ad3574.png)
c- New form "Empresas" is launched. 
d- Write a number as Nit (It should be recorded also as key_question but it didin´t..)
e- Write a company name
f- Form "Empresas" is completed and closed
g-Form "Reporte de Incidentes"  is completed and closed
2- Check in analysis.
 key_question in parent form is EmpresaA. It should contains NIT number, but it does not.
This form has not being changed and worked fine mid september.
![image](https://user-images.githubusercontent.com/29519901/65817075-a5a0d300-e1c8-11e9-99a2-508155906ab8.png)

**Comment by atl2017** [comment]
Tested with new example and it is wotking..

![image](https://user-images.githubusercontent.com/29519901/69907871-c1cd1600-13ab-11ea-956d-e0b494c2c201.png)
