### ISSUE TITLE
FT - PERSIST tasks are not being displayed in new devices if repeats > 0

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#528]
### Actual Behaviour:  I have logged in FT again with a user that have a persistent tasks that have been started before (repeats are 1). Task is not displayed not matter it is active in server.
Task is visible in Web Forms but not in FT.

Server: 
![image](https://user-images.githubusercontent.com/29519901/65816734-0a5a2e80-e1c5-11e9-8c39-446626f0676c.png)

WebForm: OK
![image](https://user-images.githubusercontent.com/29519901/65816715-e0087100-e1c4-11e9-9970-510f7e03e016.png)

FT:  Persistant task not visible
![image](https://user-images.githubusercontent.com/29519901/65816750-2c53b100-e1c5-11e9-915f-5bd13906667d.png)

### Steps to reproduce the problema:
1- Create a persistant task
2- Complete once
3- Change user´s mobile for a new one different from assigned user. After an update you can see former persistant task are shown as cancelled:
![image](https://user-images.githubusercontent.com/29519901/65816839-64a7bf00-e1c6-11e9-8dde-75105213d80c.png)
4- Return user´s mobile to persistant task assigned user. Now you see your tasks excpet persistant tasks

**Comment by nap2000** [comment]
Persistent tasks are retained on the device when they are first completed.  If the user changes device they will need to be assigned a new task.  Why is this a HIgh priority?

**Comment by atl2017** [comment]
It was tag as High due to for me it is a bug.

What is going to happen with a device that it is used for more than one user (one job multiple users) like shift foremen?

**Comment by atl2017** [comment]
> It was tag as High due to for me it is a bug.
> 
> What is going to happen with a device that it is used for more than one user (one job multiple users) like shift foremen?

Understood. Thanks
