### ISSUE TITLE
HIGH - WEB FORM - ENHANCEMENT - Prevent sending forms with lost images

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#531]
### Actual Behaviour: It is permitted to save and "send" form with lost images. Situation is that Errors are displayed and none data are saved.
![1](https://user-images.githubusercontent.com/29519901/66109954-532a3280-e58b-11e9-92af-8d27f2ba1201.png)

### Steps to reproduce the problem
Just with any web form with more than one image widget. Upload images with > 5 MB size as a whole. Save as draft and reload form. You can see that all or some are not displayed as uploaded. Save and send it and you can see thst record was not uploaded to server and also you cannot recover it.

**Comment by atl2017** [comment]
It looks like #469 but for web. form

**Comment by atl2017** [comment]
Neil,

I do not what is really happening, but there are many reported cases of lost of information in Web Forms. Could yopu please take a look of this:
Organisation: SERACIS  Project: Gestión Riesgos:  Below record was today.
![image](https://user-images.githubusercontent.com/29519901/69572840-f9465780-0f92-11ea-9dbb-46767dc42aac.png)

**Comment by nap2000** [comment]
Web forms has limits on the sizes of images that can be sent.   In particular if the user saves as draft and then restarts.  It is recommended that if you are uploading images you complete the survey without saving as a draft.

**Comment by atl2017** [comment]
Understood but we need to display warnings and more information to prevent issues.

**Comment by atl2017** [comment]
Apparently now is OK

**Comment by atl2017** [comment]
If images are bigger than 5 MB and they are saved as draft, images got lost. > 5MB should generate an error message prior to be saved as draft:  Example: "If there are images bigger tha 5 MB, they will be lost--"

![image](https://user-images.githubusercontent.com/29519901/77837311-4f87fa80-712d-11ea-93c2-9371427b98aa.png)

**Comment by nap2000** [comment]
I think I can fix the 5MB limit. Am looking at this now.

**Comment by atl2017** [comment]
oK. Pending to test

**Comment by atl2017** [comment]
First testing Ok.  Thanks!
