### ISSUE TITLE
QUICK? ENHANCEMENT - When key policy is replace note it as reason

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#546]
### Actual Behaviour: Replace is noted as merged in reason
![1](https://user-images.githubusercontent.com/29519901/69302175-c3961d00-0be6-11ea-9d25-eb52b28117bf.png)

**Comment by atl2017** [comment]
Organisation: Kontrolid
Project: TestAlex
Form: TestReplace

Not big deal, but displayed messages can prevent unexpected behavior i.e a bad key policy assignment:
![image](https://user-images.githubusercontent.com/29519901/71822381-b338e500-3062-11ea-8b08-0f71e914a171.png)

**Comment by nap2000** [comment]
I have also added translations for these "reasons": merge, replace, discard.

**Comment by atl2017** [comment]
Tested Ok. Thanks
