### ISSUE TITLE
HIGH - json_data from task API link should include metadata 

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#547]
### Expected Behaviour: json_data from task API should include not only form data but metadata too
![image](https://user-images.githubusercontent.com/29519901/69383309-4969a500-0c87-11ea-819f-4dce9cfd5b64.png)

### Actual Behaviour: Json_data link only display form data:
![image](https://user-images.githubusercontent.com/29519901/69383506-cc8afb00-0c87-11ea-8774-b1078307c9e6.png)

![image](https://user-images.githubusercontent.com/29519901/69383132-dceea600-0c86-11ea-9deb-06b37c4875c9.png)

**Comment by nap2000** [comment]
A parameter meta=yes, or meta=true can now be passed to include meta data.  Refer to http://www.smap.com.au/docs/data-api.html

**Comment by atl2017** [comment]
Tested OK
