### ISSUE TITLE
HIGH - TRANSIFEX - CONSOLE

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#552]
### Actual Behaviour:
 In english is OK but in spanish No.
English:
![image](https://user-images.githubusercontent.com/29519901/69656133-fe181380-1045-11ea-98e8-652bbf585aba.png)
Spanish:
![image](https://user-images.githubusercontent.com/29519901/69656237-30297580-1046-11ea-8749-bb065ba2508c.png)

**Comment by nap2000** [comment]
The current translation to spanish of the word "No" is "No".  So I think the code is fine.  The translation may ned looking at.

**Comment by atl2017** [comment]
Ok. But what about "Yes" at prikey # 1. It was traslated as "No" in spanish. That is the issue.

**Comment by nap2000** [comment]
Ah ok yes got it.

**Comment by atl2017** [comment]
Thanks
