### ISSUE TITLE
BUG (URGENT) - Form cannot be saved after edition

### ISSUE THREAD

**Issue by ztatu** [smap-consulting/smapserver#57]
### Steps to reproduce the problem

Just edit below form and try to save. You can´t. It shows 5 errors but those are not shown.

### Form Name: PlanillaSupervision3a

This survey works fine, but if I try to edit some question, it cannot be saved. Apparently forms have 5 errors, but them are not displayed:
![image](https://user-images.githubusercontent.com/29519901/29804190-9a54f9ce-8c46-11e7-937e-b194d7644d99.png)

**Comment by nap2000** [comment]
Click on the red button with the error count to be taken to the next error

**Comment by ztatu** [comment]
@nap2000 thanks.  I saw errors. Sorry!
