### ISSUE TITLE
ENHACEMENT - PDF dynamic appearance pdfno for non-relevant question

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#58]
### Steps to reproduce the problem
Create a form with relevant questions, check for the standard pdf template. You can see that both relevant questions and non-relevant questions are include in this report.

**Comment by ztatu** [comment]
See this specific example: Pags 3 and 4 are empty questions du to no relevance:

[Example.pdf](https://github.com/smap-consulting/smapserver/files/1270166/Example.pdf)

**Comment by atl2017** [comment]
What if we can include a property like "Skip questions with no answers" in pdf generation.

It is really useless displaying empty questions
[Conconcreto-Bodega U-Storage-1509171128.pdf](https://github.com/smap-consulting/smapserver/files/1307000/Conconcreto-Bodega.U-Storage-1509171128.pdf)

**Comment by atl2017** [comment]
@nap2000 I recommend checking this because I have some customers with the same situation.

It could be a new appereance as "pdfno_ifempty"

**Comment by nap2000** [comment]
Included in 17.08.02 (2017-09-23)

**Comment by atl2017** [comment]
Tested OK. Excellent!
