### ISSUE TITLE
H1 -BUG- WEBFORMS - Constraint is not working neither select nor acknowledge

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#587]
### Steps to reproduce the problem

(Optional) If this is reproducible on a Smap hosted server then include

### Form Name: TestConstraint WebForms

Check form and see that constraints are not working in webforms:

![image](https://user-images.githubusercontent.com/29519901/78301471-b7a85900-74fe-11ea-910b-66b0c1f8c470.png)

**Comment by nap2000** [comment]
Ok should be fixed now

**Comment by atl2017** [comment]
Tested Ok. Thanks

![image](https://user-images.githubusercontent.com/29519901/78315461-aa04ca80-7522-11ea-8104-b8071a2adbc5.png)
