### ISSUE TITLE
ENHANCEMENT - Users - Set footer position by default in 5000 for new organisations

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#594]
### Expected Behaviour: Set by default footer position to be hidden (5000 px) in new organisations

![image](https://user-images.githubusercontent.com/29519901/79593200-b9e2e980-80a0-11ea-86d6-3767bc6280d5.png)

**Comment by nap2000** [comment]
The current setting displays the footer elements correctly.  An organisation can adjust to achieve a customised style but I am no going to anticipate those requirements.
