### ISSUE TITLE
ENHANCEMENT - FT - Uncheck HiRes Video as default

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#601]
### Expected Behaviour: To avoid unnecessary high size data, I would suggest to uncheck HiRes Video as default

![1](https://user-images.githubusercontent.com/29519901/81285224-d2517e80-9024-11ea-80fa-5e58e09dbe58.png)

**Comment by nap2000** [comment]
High res video option now defaults to off for new installs of fieldTask. (Ft6.100+).  The setting can also be managed from the server at the organisation level.

**Comment by atl2017** [comment]
Tested Ok.
