### ISSUE TITLE
HIGH - WEBFORMS - url markdown is not working

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#608]
### Expected Behaviour:  url markdown should work as in enketo [https://enke.to/markdown](https://enke.to/markdown)
![image](https://user-images.githubusercontent.com/29519901/83076837-e09b2500-a03b-11ea-89a6-4e6935bf600d.png)
### Actual Behaviour: url markdown is not working:
![image](https://user-images.githubusercontent.com/29519901/83076798-cfeaaf00-a03b-11ea-9cb7-11c9bc15e566.png)

### Steps to reproduce the problem

(Optional) If this is reproducible on a Smap hosted server then include

**Comment by nap2000** [comment]
Static links work.  For example:

  [url](http://www.kontrolid.com/)

Does enketo support dynamic links in markdown built up from the answers to questions?  It is not clear from the example that they do.

**Secondly** you can build up dynamic links using HTML.  The following works:

calculate   url 'https://www.smap.com.au'
calculate  link  concat('<a href="', ${url}, '">this</a>')
note ${link}

**Comment by atl2017** [comment]
Tested Ok. Thanks

![image](https://user-images.githubusercontent.com/29519901/83261005-4db7d300-a180-11ea-9265-53ac6b47b50b.png)
