### ISSUE TITLE
H4- BUG - Cancel subscription  using email link is not working

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#617]
### Actual Behaviour:
Step by step: After cancel subscription it is not possible to reactivate account:
![image](https://user-images.githubusercontent.com/29519901/83754635-e55e6b00-a631-11ea-9f74-24ef494fdcff.png)
![image](https://user-images.githubusercontent.com/29519901/83754765-235b8f00-a632-11ea-9628-902525bb7248.png)
![image](https://user-images.githubusercontent.com/29519901/83754871-48e89880-a632-11ea-8e3d-dee4a252af07.png)
![image](https://user-images.githubusercontent.com/29519901/83754953-6fa6cf00-a632-11ea-830f-52224f998ae2.png)

**Comment by nap2000** [comment]
I am having difficulty reproducing this.  Is the problem that cancelling the subscription is not working in your example?  Who is that email sent to, the one where you get the unsubscribe link?

**Comment by atl2017** [comment]
Hi Neil.

I have tested again and it seems to cancel subscription from the link it is not working. I meant I have received a message that was not subscribed but effectively it is not happening.

If I send a new notification, it is received:

![image](https://user-images.githubusercontent.com/29519901/83983437-0655e300-a8f4-11ea-9f11-28c8f8247025.png)

**Comment by atl2017** [comment]
I have tested again deleting first he user and redo subscription. It is working:

![image](https://user-images.githubusercontent.com/29519901/90297137-2903fb00-de53-11ea-997a-40c97700315f.png)
