### ISSUE TITLE
H2 - BUG - UX- Message in FT related to Rol Access Constraint

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#62]
I wrote you this June 9th.

Hi Neil,Now I am going to use Roles to specify right to access specific forms between the same project.
--

### Expected Behaviour

How it should be: FT try to get ALL forms for users with the same project. If a form is restricted by a Role, users with that Role get the form. Rest would not receive neither any based role form nor any error message-

### Actual Behaviour:

Error Message for users without a role is annoying because is displayed every time tasks are updating (See image below).

How it works today:  FT try to get ALL forms for users with the same project. If a form is restricted by a Role, users with that Role get the form but the rest users get an error message.

### Steps to reproduce the problem

Just assign a form to a specific role and see what happen with the rest of users at the same project but without this role:

![image](https://user-images.githubusercontent.com/29519901/30064637-f972849a-9217-11e7-85f6-2dfe3f5bc8b1.png)

**Comment by atl2017** [comment]
@nap2000  How easy is to implement a solution for this. Currently I have managed specific forms for users just spliting in different projects.

**Comment by atl2017** [comment]
Neil,

I change priority to HIGH due to customer requerimente. In order to see situation just refer ro image below. As current que need to split in more than 1 project to let forms visible to one user and not to others. But with Roles we can do it easily 

![image](https://user-images.githubusercontent.com/29519901/30824593-a27e5464-a1f5-11e7-9327-7d44abdd2471.png)

**Comment by atl2017** [comment]
@nap2000 I need to made a decision. If it is fixed soon I move to use roles if not I should split forms in projects. Thanks

**Comment by nap2000** [comment]
OK I will prioritise this one.

**Comment by nap2000** [comment]
Included in version 17.09

**Comment by atl2017** [comment]
Tested OK. Thanks.
