### ISSUE TITLE
H3 - BUG - User´s trail is not working

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#621]
### Expected Behaviour: User's trail is not working. Apparently data is gotten in devices but thay are not shown in Locations:
![Screenshot_20200609_112653_org smap smapTask android kontrolid](https://user-images.githubusercontent.com/29519901/84435862-1faea600-abf8-11ea-9855-15bfa82220af.jpg)
![Screenshot_20200609_112451_org smap smapTask android kontrolid](https://user-images.githubusercontent.com/29519901/84435881-289f7780-abf8-11ea-974b-1b82efd3ede7.jpg)
![IMG-20200609-WA0015 (1)](https://user-images.githubusercontent.com/29519901/84435907-2e955880-abf8-11ea-85c5-138086502ef2.jpeg)

### Actual Behaviour: Today we have confirmed how user's trail is used: 
For example, if a supervisor checks the user´s activity and observed a dead time i.e of 2 or 3 hrs, He wants to know where the user was between submissions. I that case he moves to Location and checks user trail to audit

![image](https://user-images.githubusercontent.com/29519901/84433959-bf6a3500-abf4-11ea-9946-8c3f8e415cd5.png)

**Comment by nap2000** [comment]
I think I will add the user to the user locations view in the dashboard.  However as an interim for the next release i hav removed project from the user trail page.

**Comment by nap2000** [comment]
A problem was that the usr trail was not sent if no task information had changed since the last refresh.   Fixed in F 6.202

**Comment by atl2017** [comment]
Tested OK. It works with FT 6.204
