### ISSUE TITLE
H2- HIGH - BUG - Files are not being displayed in Analysis after completion for tasks based on previous data 

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#626]
### Actual Behaviour: It is working fine for Images but not for Upload files. I mean it is visible in webforms but not in analysis

Organisation: Kontrolid  Project:TestTasks  Forms: File1 & File 2  TaskGroup: TestFile
![image](https://user-images.githubusercontent.com/29519901/85014998-d943d480-b12c-11ea-886e-bc0b2958eed0.png)
When click
![image](https://user-images.githubusercontent.com/29519901/85015148-19a35280-b12d-11ea-8979-0db988633341.png)

**Comment by nap2000** [comment]
The file from the first survey is now passed correctly to the second survey.  This works on fieldTask as well as Webforms.  Hence you can submit a file from a webforms app and it is viewable in fieldTask.

Note only new submissions of a file are fixed.  I have not fixed old data.

**Comment by atl2017** [comment]
Tested OK. Thanks
