### ISSUE TITLE
Nepali font support in generated pdf

### ISSUE THREAD

**Issue by Rajen2020** [smap-consulting/smapserver#629]
### Component fieldTask or SmapServer
Generated PDF Report
### Version
20.5
### Expected Behaviour
Nepali unicode font support. Should be able to use Nepali unicode font.
### Actual Behaviour
Nepali Unicode font not being supported in generated pdf report.
### Steps to reproduce the problem

(Optional) If this is reproducible on a Smap hosted server then include

**Comment by Rajen2020** [comment]
Hi friends,
Relatively shorter forms without repeating group can have a nice customized pdf report; I would also suggest so. However, forms with repeating subform whose number of repeat is unknown at the time of form authoring cannot use a customized pdf template because how much data is coming into is also unknown. The issue is, when I am using generated pdf for forms that have repeating subforms, data cannot be written in Nepali language. So local font support should be added.

**Comment by nap2000** [comment]
Released on your server.   I have also fixed the issue with landscape PDFs from the console.

**Comment by Rajen2020** [comment]
Hi Neil, thanks for the important releases. Great, working. Please fix the issue of using html tags with Nepali labels, also.
