### ISSUE TITLE
BUG - Duplicated FORMS displayed at FT

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#63]
### Actual Behaviour

I have tested to replicate duplicated forms. I am still not sure what conditions should have to happen.

I created a new form from zero (Form1) with editor but behaviour is what expected. On the other hand I upload ReporteDiario and after every edition a new version is displayed but the first version (in this case v:2) remains each. Below 3 screenshoots after every changes::

![image](https://user-images.githubusercontent.com/29519901/30065140-8f8b5582-9219-11e7-8d87-f94a6007ed42.png)
![image](https://user-images.githubusercontent.com/29519901/30065155-9705b492-9219-11e7-80df-c02fc934ca48.png)
![image](https://user-images.githubusercontent.com/29519901/30065166-9e1b0700-9219-11e7-8305-284be9c41716.png)

### Steps to reproduce the problem

You can modify by yourself this form (or all) in this project: TestAlex (Zarkman) to see whay happen..

**Comment by nap2000** [comment]
Has ReporteDiario been deleted as I can't see it?  I tried modifying Control_de_Puestos but did not see the behaviour you described.

**Comment by atl2017** [comment]
Yes it was deleted but I uploaded again. I tried to reproduce the problem again but I could not.

I am not sure if something related to resources you fixed have helped.

What I see with this particular form is that it uses external data (6000 records .csv file).

**Comment by nap2000** [comment]
Its possible that the fix I put in place does not work for existing forms only new ones.

**Comment by atl2017** [comment]
tested  with FT5.03 and again happens. See screenshoot:

![screenshot-1504802594071](https://user-images.githubusercontent.com/29519901/30174796-e0d2339e-93c1-11e7-8354-6ba3a0d29d3f.jpg)

**Comment by atl2017** [comment]
Apparently it has been fixed with new release.
