### ISSUE TITLE
BUG - WEB FORMS - Select choices are not visible at first time. It is needed double refreshign page

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#630]
### Actual Behaviour: In order to see choices, it is necessary to refresh twice:
First time page is displayed:
![image](https://user-images.githubusercontent.com/29519901/86199141-f14d2800-bb1e-11ea-9aec-a649d3c8b867.png)
After F5 (Refreshing page):
![image](https://user-images.githubusercontent.com/29519901/86199194-1772c800-bb1f-11ea-9718-8b5c1fa0a7fc.png)

**Comment by nap2000** [comment]
I could not reproduce this.  Its possible that the first time the survey was downloaded the javascript files for webforms were also being downloaded and there was a timout.

**Comment by atl2017** [comment]
I have download xlsform and upload it again. I could reproduce the issue. Please try it again or download/upload the form.

**Comment by atl2017** [comment]
Tested with sg server 21.0 and works fine.
