### ISSUE TITLE
Field-list option not working with pdfhideindex 

### ISSUE THREAD

**Issue by Rajen2020** [smap-consulting/smapserver#632]
### Component fieldTask or SmapServer
FieldTask
### Version
6.103
### Expected Behaviour
field-list option should work together with pdfhideindex because data enumeration would be very comfortable when being able to see all questions under a repeating subform in single page of FieldTask for better referencing and quality data collection.
### Actual Behaviour
When I add field-list option before/after the pdfhideindex option, all questions under that repeating subform cannot be seen on a single page of FieldTask.
### Steps to reproduce the problem
When I add field-list option before/after the pdfhideindex option, all questions under that repeating subform cannot be seen on a single page of FieldTask.
(Optional) If this is reproducible on a Smap hosted server then include

### Server
As specified
### Organisation
As specified

**Comment by nap2000** [comment]
Released in 6.204 which is now in google play
