### ISSUE TITLE
ENHANCEMENT - STANDARD PDF - PART 2

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#635]
Really great!

1- Is it possible to hide instancename if it is set as title?
2- Is it possible to hide user because it is include as footer?
3- What about include timestamp  Created: yyyy-mm-dd hh-mm ( Upload time)
                                                        Printed:  yyyy-mm-dd hh-mm ( Now when download)

![image](https://user-images.githubusercontent.com/29519901/86846734-e8091180-c070-11ea-9503-d1983db4b352.png)

_Originally posted by @atl2017 in https://github.com/smap-consulting/smapserver/issues/599#issuecomment-655154139_

**Comment by atl2017** [comment]
@Rajen2020 commented:

Good idea, atl2017. However, if possible the 'Completed by' at the footer of report should be optional while setting the form. Because, sometime the printed copy of generated pdf should have another signatures like, 'Prepared by' or/and 'Approved by' etc. So, we need to put those phrases for places to get the signatures.

@Rajen2020
 
Rajen2020 commented 11 days ago • 
I would take another liberty here to suggest little but important enhancement in the generated pdf. Would it be possible to make the value bold like label? Because, say- Grand Total and 250,000.00 (say) should be displayed in bold. At least for numeric value!

**Comment by atl2017** [comment]
Also:

Is it possible to set title in 3 lines to avoid cut text:
![image](https://user-images.githubusercontent.com/29519901/87863273-10b9c280-c91f-11ea-9ee4-66b6971de982.png)

**Comment by atl2017** [comment]
1- & 2- Tested OK.

Now I have found that there is still one parameter that we would like to format. That is _hrk when it is present.

Proposed alternatives: 1- Include as part of footer below to user

 2- Include _pdfheader_ and _pdffooter_ as position

![image](https://user-images.githubusercontent.com/29519901/87877736-a4ce6d00-c9a5-11ea-9b78-7003366bb840.png)

**Comment by nap2000** [comment]
I have made the programming changes requested.  I just ned some translations to be done.

**Comment by atl2017** [comment]
Tested OK. Awesome.

I will move pending 3- as new issue.
