### ISSUE TITLE
ENHACEMENT - automatic refreshing for TASKs

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#65]
### Expected Behaviour

Editing or creating new task should syncronise automatically at FT5

check/uncheck "task only" property in a specific project should syncronise automatically at FT5

After "Delete Saved Form" at FT one should click refreshing task manually. I am not sure if this action should be include in automatic.

After instalation of a new release, username / password remains, but Task List remains empty no matter Autosend is activated.

**Comment by atl2017** [comment]
Ok, 

DOES NOT synchronize when tasks are completed by webforms:

![image](https://user-images.githubusercontent.com/29519901/30481490-a1491e12-99e4-11e7-9581-cb6bf887d921.png)

**Comment by atl2017** [comment]
Also check / uncheck Tasks Only does not refresh automatically

**Comment by nap2000** [comment]
Point 1 completed. Other issues should be raised separately.
