### ISSUE TITLE
FT5- Pending traslations

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#67]
### Version 5 (Beta)

Requiered Traslation

![image](https://user-images.githubusercontent.com/29519901/30066201-cb8ec3d6-921c-11e7-8bab-4913a0479cad.png)

![image](https://user-images.githubusercontent.com/29519901/30066219-db2a35a0-921c-11e7-931f-42b43cc00447.png)

![image](https://user-images.githubusercontent.com/29519901/30066365-48a770f2-921d-11e7-9f85-34d99ff3751b.png)

Also erase any reference to ODK at splash screen and "ODK" username to avoid confusion

![image](https://user-images.githubusercontent.com/29519901/30066379-52d41332-921d-11e7-8c88-980690c9f973.png)

**Comment by nap2000** [comment]
These are missing ODK translations - can you update in https://www.transifex.com/opendatakit/collect/ then I will update fieldTask

**Comment by atl2017** [comment]
Done!
