### ISSUE TITLE
Browse Results - Charts

### ISSUE THREAD

**Issue by ztatu** [smap-consulting/smapserver#7]
### Steps to reproduce the problem:

Use any data and select a question to display

### Form Name: ReporteDiario

![cambiar mapatest chartchart test20](https://user-images.githubusercontent.com/29519901/27261174-fd0d3792-5402-11e7-88ea-f97e2efb8799.png)
![cambiar mapatest chartchart test21](https://user-images.githubusercontent.com/29519901/27261175-0c2ed3ca-5403-11e7-8385-bdea4fdb2433.png)

**Comment by ztatu** [comment]
Neil,

What I need is just to have charts as before. Today data are only aggregated

![average survey completion time1](https://user-images.githubusercontent.com/29519901/27404201-ce0d80a4-5692-11e7-9815-25661856a968.png)
![puesto3](https://user-images.githubusercontent.com/29519901/27404203-ce133f08-5692-11e7-8003-b2cc1a4ff724.png)

**Comment by nap2000** [comment]
Should be fixed now. This problem was occuring with question names that had capitals.

**Comment by ztatu** [comment]
Tested: OK Thanks. 

![image](https://user-images.githubusercontent.com/29519901/27441200-6a0fefba-5732-11e7-8ae7-e6baae4a22b0.png)
