### ISSUE TITLE
HELP - Error importing file

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#71]
### Actual Behaviour: I just exported data and without doing anything else I tried to upload to another project with the same form.

Following message were displayed:

![image](https://user-images.githubusercontent.com/29519901/30074010-77dc05dc-9235-11e7-8f2d-a6517b735b7e.png)

### Form Name: Control_de_Puestos

I will send .zip file by wetransfer

**Comment by nap2000** [comment]
I loaded the data into the empty Control de Puestos form in TestAlex.  There was an error reported after quite a long time due to the client timing out.  However the data was added. Not sure where the "undefined" error you saw came from.

**Comment by atl2017** [comment]
I saw it.

I erased data and do it again but fail:

![image](https://user-images.githubusercontent.com/29519901/30115401-377eafca-92e0-11e7-80a8-ce6fcde93069.png)

**Comment by nap2000** [comment]
Yep but the data's there.  The client timed out before the upload had finished processing.  I should increase the length of the timeout or process the data through a secondary batch.

**Comment by atl2017** [comment]
OK. Thanks

**Comment by atl2017** [comment]
Again with other file:

![image](https://user-images.githubusercontent.com/29519901/30522893-01cdd9f8-9b9d-11e7-873f-3be336548859.png)

Organisation: SERACIS

Project: Pruebas

Form Name: F24 - SEGFIS - Supervision

I think is related to size (2 gb) because I tested with just simple data.xls and 6 images and works.

Is there any limitation.

I will send file by wetransfer

**Comment by nap2000** [comment]
It looks like a timeout issue again.  In this case the file may have been sufficiently large that the upload did not complete before the connection timed out.  Previously the upload had completed and the timeout happened during file processing.  The result being that the data was loaded OK but you got an error message.

There are no specific limitations with respect to size.  I will have a look a increasing the timeout settings however the amount that can be uploaded before an error will still depend on the speed of your internet connection.

Would it be possible to split your upload into roughly 50 to 100 MB zip files.  

regards

Neil

**Comment by atl2017** [comment]
Ok. But regarding to split my load is theoretically posible, but practically very tedious considering that images are named using uuid.

Maybe is good to consider as I wrote in #69 using a filter to expor data by this way.

It happens frequently that users starting using application, mix test data with production data  and when finally moves from test to production wants to erase garbage data. These what it happens with this specific example.
