### ISSUE TITLE
L1 - ENHACEMENT- UX- Prevent going back in answered questions

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#75]

**Comment by nap2000** [comment]
The collect team are currently working on this https://forum.opendatakit.org/t/how-can-i-avoid-backscattering/9198/10.  I will incorporate it when it is available.

**Comment by atl2017** [comment]
Now it is avaliable in ODK Collect v1.12.0 beta at User Level through Admin setting. When you upgrade FT to this I recommend you to also set Admin Setting with password.

**Comment by atl2017** [comment]
Thanks
