### ISSUE TITLE
PDF - QUICK? - ENHANCEMENT- Map point color at pdf template

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#78]
### Actual Behaviour: gray color

![image](https://user-images.githubusercontent.com/29519901/30377087-2c375ff8-9854-11e7-92b1-9a314de8fd9d.png)

**Comment by atl2017** [comment]
Yes please.

**Comment by atl2017** [comment]
@nap2000 Not big deal but if it is easy..

**Comment by atl2017** [comment]
Another customer request the same. I would recommend this. It is true that gray color is hide from the rest of map details. It should be red.

![image](https://user-images.githubusercontent.com/29519901/45215287-9fa91e80-b262-11e8-8f23-5218dfca138b.png)

**Comment by nap2000** [comment]
Noted

**Comment by nap2000** [comment]
The color of the marker can now be set as an appearance on the question:  pdfmarkercolor_rr_gg_bb

**Comment by nap2000** [comment]
The default color has also been set to red

**Comment by atl2017** [comment]
Great. Thanks!    Tested OK
