### ISSUE TITLE
FT5.03 Beta - Tasks are not working properly

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#79]
### Actual Behaviour

1- When you work autosend off (both server and app), if you accomplish a task, saved form is not visible when you click "Send Finalized Form":

Below two filled forms (same) but one was filled directly as a form and the other assign as a task. If you check Send Finalize Form, only filled form is displayed:
![screenshot-1505306837586](https://user-images.githubusercontent.com/29519901/30378558-4144e99c-9859-11e7-9458-c5263859ebe1.jpg)
![screenshot-1505306859769](https://user-images.githubusercontent.com/29519901/30378616-6d046242-9859-11e7-9940-433a8c1f999a.jpg)

2- If you do a hold click at a task, menu accept / reject is not shown

**Comment by atl2017** [comment]
Reject Tasks OK.

Complete Task button does not produce any result

![screenshot-1505475550271](https://user-images.githubusercontent.com/29519901/30480920-d72db41e-99e1-11e7-9731-fd9dd014506a.jpg)

**Comment by nap2000** [comment]
A separate issue should be raised for this.
