### ISSUE TITLE
BUG2 -TASKS - Empty Group name is permitted?

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#82]
### Steps to reproduce the problem

![image](https://user-images.githubusercontent.com/29519901/30482463-c9df48de-99e8-11e7-80ca-899bc25f4589.png)

**Comment by nap2000** [comment]
Included in 17.08.01

**Comment by atl2017** [comment]
OK. It is not possible to continue after message but error is not clear for user. It should be something like "Group Task missing"

![image](https://user-images.githubusercontent.com/29519901/30774948-f7c032c8-a04f-11e7-8713-14520a671417.png)

**Comment by atl2017** [comment]
It happens first time when no group task have been created. Solution I recommend: To hide "Add Tasks" if there is any group task.

**Comment by atl2017** [comment]
Pending


![image](https://user-images.githubusercontent.com/29519901/31361822-eccbcf12-ad1a-11e7-9e05-7a2380f3e55f.png)

**Comment by atl2017** [comment]
@nap2000 I recommend this because first thing user try to do is Add Task and forget that needs to create  task group first.  Another alternative is to create a name by Default like "Group" and also switch menu items: Tasks and Task Groups in order to understand what is first.

**Comment by atl2017** [comment]
You should remove "release" label

**Comment by nap2000** [comment]
Ok.  Should be fixed in v1710b

**Comment by atl2017** [comment]
tested OK
