### ISSUE TITLE
ENHANCEMENT - TASKS Icon for saved forms equal to task

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#85]
### Actual Behaviour: I have not remembered that saved forms either by Icon or menu before closing is shown with the same icon as a task. Should we changed this Icon to differentiate? Like draft forms

How can establish priority for user that instead of filling new form first finish an edited one. What about display Tasks block first? (Maybe include another check like Task Only in project to sort blocks (First Tasks or First Forms)

![screenshot-1505482261498](https://user-images.githubusercontent.com/29519901/30485938-9bb3af84-99f4-11e7-8ead-3fd15083b1eb.jpg)

**Comment by atl2017** [comment]
Maybe it could be included a text in the third line indicating "Saved Form" (Italic) to differentiate to other tasks

**Comment by nap2000** [comment]
Not sure.  The concept was that selecting a form on the phone completes a "local" task as opposed to a task downloaded from the server.  Hence if you save it then it is shown with the task icon.  So if you want to differentiate local tasks or perhaps "in progress" tasks then maybe you could propose a new icon.

**Comment by atl2017** [comment]
Understood
