### ISSUE TITLE
WebForms

### ISSUE THREAD

**Issue by ztatu** [smap-consulting/smapserver#9]
### Steps to reproduce the problem

See column: VBGerenciaOperaciones last record at below image. 

### Form Name:  Salida de Materiales y Equipos V2

![image](https://user-images.githubusercontent.com/29519901/27348442-aec7af3c-55b9-11e7-8950-f2e2a888bf3b.png)

**Comment by nap2000** [comment]
Not updating the images is a problem that has been introduced with the new version of webforms. I will make this a high priority issue.

**Comment by ztatu** [comment]
Please also check deviceid and/or username. I need a way to certificate authoring of survey from webform

**Comment by nap2000** [comment]
I'm not seeing the issue with username.

**Comment by nap2000** [comment]
New images are now included in the updated record.   

DeviceId, and username preloads are not set by webforms at the moment.  Note the User who submitted the form is available automatically in the _user field of the results.  If you need this behaviour changed can you raise a separate issue.
