### ISSUE TITLE
QUESTION- select_one from external instead of search csv

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#90]
### Steps to reproduce the problem
I upload example from  [xlsform.org](https://docs.google.com/spreadsheets/d/12qZL34kuHSZGWDv0BBJ1qf7dSmml-d2VnMWH0Vtg-O4/edit#gid=683809272)

external selects were converted to text question

![image](https://user-images.githubusercontent.com/29519901/30512565-fd1bb08c-9ab7-11e7-97d8-b5cabf807975.png)

**Comment by nap2000** [comment]
External datasets are commonly used for cascading selects. You can add a filter to do this. Hence the first select may have the following appearance:  "search('country')"  which will show all the unique values from the country column in the CSV file.

The second select may have an appearance of "search('district', 'matches', 'country', ${country})"  This will show all unique values in the district column where the country column has the value chosen in question 1.

The third select may have an appearance of "search('town', 'matches', 'district', ${district})" and so on.

By the way this is not the appropriate forum for asking questions.  Only issues.

**Comment by atl2017** [comment]
Thanks
