### ISSUE TITLE
BUG - PDF Including html tags to change styles in question cause pdf crashes

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#91]

**Comment by atl2017** [comment]
I solved temporary by basically include a pdfno to this question

**Comment by atl2017** [comment]
Not big deal. Normally when I use a lot of html tags in questions I hode those prfo pdf

**Comment by nap2000** [comment]
Still crashes are not good. I will fix this one.

**Comment by nap2000** [comment]
HTML tags work fine.  The problem in this case was that the html was wrong.  Ie you used </br> when it should have been <br/>.  I didn't put </br> in my documentation did I?  You can see the error message that gets generated by select "Logs" from the admin menu.

**Comment by atl2017** [comment]
Neil, thanks for feedback.

You were right I mistyped </br> instead of <br/>
