### ISSUE TITLE
FUTURE - PDF- ENHANCEMENT - PDF - Self signed documents

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#94]
### Expected Behaviour: While we can include a more sophisticated solution fo Digital Signatures issue by a trusted certified authority, we can include a self-signed solution just stamping directly from server with some metadata that help to confirm authenticity, integrity and non-repudiation.

metadata could be: Record - user - upload (local time) - device - survey name and version
![image](https://user-images.githubusercontent.com/29519901/30778682-af83d620-a0a1-11e7-9264-b88290169645.png)

As the an optimual solution should be:

![digitalsignatures](https://user-images.githubusercontent.com/29519901/30778720-65065978-a0a2-11e7-8926-2b785cc09256.JPG)

**Comment by atl2017** [comment]
Additional comments

1- As first we could add a time stamp in standard pdf template below "Completed by.." (In fact it should be traslated) and better if it is synchronise to official time to colombia  horalegal.inm.gov.co (http://186.155.28.147/). Also I am not sure if there is a tracking system if a form it is edited by Edit Web Forms, that can be included as part of our system to integrity assurance.



2- Same as 1- but to be included at customised pdf (must be check at organisation level)
3- If 1 and 2 works, next step could be certify by a trusted third-party for legal reasons

**Comment by atl2017** [comment]
Suggestion: To include a parameter by Organisation

![image](https://user-images.githubusercontent.com/29519901/39429753-832c4876-4c51-11e8-8c83-f0651c17c2a5.png)

**Comment by nap2000** [comment]
Printed or generated?

Le sam. 5 mai 2018 3:20 PM, Alexander Torrado <notifications@github.com> a
écrit :

**Comment by atl2017** [comment]
Good question.  Maybe both or at least Generated.

Generated = Upload Time (Local) + some delayed time server

Printed Time = Local Time when a PDF is download either by Analysis or Report (.zip) or was sent by Notifications (Email).  I supossed Restore Data would change all times

Example:
1) 2018-05-02 Form is uploaded and PDF sent by Email

Time Stamp: _PDF Printed at 2018-04-025 10:03 (LOCAL TIME) as  was Generated at 2018-05-02 10:03)_

2) 2018-05-03 Someone download PDF from Analysis or as Report 

Time Stamp: _PDF Printed at 2018-05-03 09:30 as was Generated at 2018-05-02 10:03)_

3) 2018-05-04 Someone update record either Edit in WebForm  or Modified or other method and then download PDF from Analysis or as Report 

Time Stamp: _PDF Printed at 2018-05-04 14:30 as was Generated at 2018-05-04 14:30)_

4) 2018-05-03 Someone download PDF from Analysis or as Report 

Time Stamp: _PDF Printed at 2018-05-054 09:30 as was Generated at 2018-05-04 14:30)_

So, if someone had received copy 1) as original could evidence changes against 3)

**Comment by atl2017** [comment]
Well, I know we have had other priorities but this look very useful to increase trust in our solution.

**Comment by atl2017** [comment]
Now that you have implemented console sucessfully. I think it should be relevat to include a timestamp to guarantee traceability of "printed" and "generated" documents.
