### ISSUE TITLE
FUTURE - L6 - ENHANCEMENT - NOTIFICATIONS Let Write Email Body text in markdown

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#95]
### Actual Behaviour. Only plain text to write Email body text is permitted causing some issues with accented characters and more.

![image](https://user-images.githubusercontent.com/29519901/30779178-b80b5ef0-a0ae-11e7-8edb-0a12e89ff456.png)

**Comment by atl2017** [comment]
The idea is to avoid something like this:

![image](https://user-images.githubusercontent.com/29519901/30838088-159d12b2-a22f-11e7-9b04-16174098510f.png)

**Comment by atl2017** [comment]
Due to current code, some subject are received like below (does not understand ñ) 

![image](https://user-images.githubusercontent.com/29519901/31076860-ecfc2e48-a741-11e7-9c95-0f4a11a7266f.png)

**Comment by atl2017** [comment]
@nap2000 Not big deal you can decide to maintain or close without action

**Comment by nap2000** [comment]
Seems worthwhile
