### ISSUE TITLE
FUTURE - ENHANCEMENT - 17.12.  Include Version Note in Replace and modified by column

### ISSUE THREAD

**Issue by atl2017** [smap-consulting/smapserver#98]
### Expected Behaviour: If a Company has a very good documentation practices, it would be necessary to record all changes of a form no matter if the new one is upload from xlsform instead of edit in editor. So instead of avoid uploading a duplicate form, it could be interesting to replace and  record traceabiity of this change.  Also we can include some "comments" of  Purpose/Change  and create some kind of version control table

![image](https://user-images.githubusercontent.com/29519901/30779596-7bcf4080-a0ba-11e7-8080-4d922a3ef8b7.png)

![image](https://user-images.githubusercontent.com/29519901/30779584-42612d90-a0ba-11e7-876f-93b92139d88e.png)

**Comment by atl2017** [comment]
Neil,

With your latest feature about  could be nice to include a text box for notes about version and in the forms list include a column with user (modified by)

![image](https://user-images.githubusercontent.com/29519901/35149623-d7c0fe8e-fce4-11e7-8d19-fed575619e4a.png)
![image](https://user-images.githubusercontent.com/29519901/35149674-0630e310-fce5-11e7-8a04-b4203f3f4639.png)
![image](https://user-images.githubusercontent.com/29519901/35149737-46a0b7ae-fce5-11e7-8014-8451249c74aa.png)

**Comment by atl2017** [comment]
Due to your recent advances in this matter (Replace) I would consider that this proposal it is useful.  

Maybe addtional information could be better include in Info:

![image](https://user-images.githubusercontent.com/29519901/38738342-94a3f322-3ef7-11e8-85bc-16b057814c2c.png)

**Comment by atl2017** [comment]
What do you think?

**Comment by nap2000** [comment]
Yep.  I need to do some work on this.  Including being able to review the history of these changes. Its pretty urgent.   A note might be useful particular if it can be edited later.  Ie when the user is reviewing their history of changes and considering what to make of them.

**Comment by atl2017** [comment]
After your recent release, my suggestion is to include a text box to include "Reason for change". It is the business reason behind replacement. I.e: "Include legal statement ....."
